// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `asr_provider`, `global`, `launch_editor`, `open_fake_feed`, `token_scripts`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Global`, `InserterSlot`, `SpeechSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Build the engine behind the bridge with the real default microphone
/// and, when the `[asr]` config yields an API key, the Aliyun realtime
/// adapter streaming real transcripts. Without a key the mic+VAD provider
/// keeps the session semantics (speech activity, silence, device
/// failure). The rectify LLM is the real OpenAI-compatible client when
/// `[llm]` yields a key; the scripted demo LLM otherwise — but that
/// combination is refused under a real ASR key (see `engine_factory`).
/// Insertion is the production inserter (clipboard paste with restore, or
/// typing per the `[insertion]` config). Session semantics load from the
/// `[engine]` section of the layered config files. Idempotent: a second
/// call is a no-op.
Future<void> createEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiCreateEngine(llmResponses: llmResponses);

/// Build the engine behind the bridge with all-fake collaborators.
/// `llm_responses` become the scripted rectify responses (streamed in small
/// chunks), repeating forever — the demo host never runs dry no matter how
/// many sessions or rerolls come. Idempotent: a second call is a no-op.
Future<void> createFakeEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiCreateFakeEngine(llmResponses: llmResponses);

/// Submit a command to the engine. Returns an error only for rejected
/// commands (wrong state); asynchronous outcomes arrive on the event stream.
Future<void> execute({required BridgeCommand command}) =>
    RustLib.instance.api.crateApiExecute(command: command);

/// Current session state, for initial paint before any event arrives.
Future<BridgeSessionState> state() => RustLib.instance.api.crateApiState();

/// Passage mode as it stands now (config-seeded, runtime-switched) —
/// what the quick panel's toggle paints and what the next session opens
/// with.
Future<bool> passageMode() => RustLib.instance.api.crateApiPassageMode();

/// Hand the keyboard back to the remembered target window — the quick
/// panel's own close path. Self-guarded on the inserter side: a foreign
/// foreground (or no remembered target) is left alone, exactly like the
/// cancel-path restore. No-op on the fake engine.
Future<void> restoreFocus() => RustLib.instance.api.crateApiRestoreFocus();

/// The hotword dictionary as it stands now, in file order — the quick
/// panel's term chips. File-level, engine-independent (the engine
/// re-reads the file when the next session opens, which is what makes a
/// quick-added term live for that session).
Future<List<String>> termsList() => RustLib.instance.api.crateApiTermsList();

/// Quick-add one term to the dictionary (idempotent; blank rejected).
/// See [`spokenrectifier_config::terms::append_term`] for the placement
/// and repair rules.
Future<void> appendTerm({required String term}) =>
    RustLib.instance.api.crateApiAppendTerm(term: term);

/// Remove a term from the dictionary (a no-op when absent).
Future<void> removeTerm({required String term}) =>
    RustLib.instance.api.crateApiRemoveTerm(term: term);

/// The scenario library (场景库): user-named style directives from the
/// app-owned `spokenrectifier-scenarios.toml`. A missing or corrupt file
/// reads as an empty library — this never errors and never writes. The
/// shell paints its pickers from the list and resolves the selected
/// entry's directive text itself (selection lives app-side, never
/// persisted; ADR-0004).
Future<List<BridgeScenario>> scenarios() =>
    RustLib.instance.api.crateApiScenarios();

/// Save the whole scenario library — the settings editor's model,
/// wholesale — into the file the loader resolves (created in the app's
/// settings home when no library exists yet). File-level and
/// engine-independent like [`scenarios`]: the pickers re-read the library
/// after a save; the selected scenario's directive rides the next
/// `SetStyleDirective` as usual. Only ever runs on a user action (the
/// editor's add/edit/delete), never on load.
Future<void> saveScenarios({required List<BridgeScenario> scenarios}) =>
    RustLib.instance.api.crateApiSaveScenarios(scenarios: scenarios);

/// Everything the fake inserter received, in order (demo introspection).
/// The production inserter does not record; insertion outcomes arrive on
/// the event stream instead (`TextInserted` / `Error`).
Future<List<String>> insertedTexts() =>
    RustLib.instance.api.crateApiInsertedTexts();

/// The most recent stored sessions, newest first — the history panel's
/// content. Empty in the keep-nothing mode (and on the fake engine).
Future<List<BridgeHistoryEntry>> historyList() =>
    RustLib.instance.api.crateApiHistoryList();

/// Remove every stored session — the tray's one-click clear. A no-op in
/// the keep-nothing mode.
Future<void> historyClear() => RustLib.instance.api.crateApiHistoryClear();

/// The effective `[history]` settings from the layer files — the
/// settings window's history pane initial paint.
Future<BridgeHistoryConfig> historyConfig() =>
    RustLib.instance.api.crateApiHistoryConfig();

/// Write new `[history]` settings and apply them to the live store at
/// once (the settings window's 保留期 / 不留存 controls): the file edit
/// is section-preserving in the layer that owns the effective values,
/// and the store adopts the new config immediately — a tightened
/// retention sweeps at once, keep-nothing wipes, and turning it back on
/// resumes recording. Returns the re-read effective config.
Future<BridgeHistoryConfig> setHistoryConfig({
  required bool enabled,
  required BigInt retentionDays,
}) => RustLib.instance.api.crateApiSetHistoryConfig(
  enabled: enabled,
  retentionDays: retentionDays,
);

/// Start one fidelity-eval run in the background — the settings window's
/// manual entry. Every case rides the event stream; the run ends with
/// `Finished` or `Failed`. Dropping the Dart listener (window closed,
/// pane cancelled) aborts the run at the next case boundary. Only one
/// run at a time: a second call while running is an error.
///
/// The run builds its own engine instance (noop inserter, no history
/// recorder, the suite's fixed term list) against the real configured
/// LLM — the app's live engine is never touched, so the eval neither
/// inserts text nor pollutes history (the sr-eval seam, in-process).
Stream<BridgeEvalEvent> startFidelityEval() =>
    RustLib.instance.api.crateApiStartFidelityEval();

/// Open the shared config file in the system text editor — the tray's
/// settings entry. Creates a commented stub first when no config file
/// exists yet (see `settings::ensure_shared_config` for where). Returns
/// the path that was opened.
Future<String> openConfigFile() =>
    RustLib.instance.api.crateApiOpenConfigFile();

/// Subscribe the Dart side to the engine's event stream. Each call spawns
/// an independent forwarder; dropping the Dart stream stops it.
Stream<BridgeEventEnvelope> subscribe() =>
    RustLib.instance.api.crateApiSubscribe();

/// Open the next fake ASR session and allow `fake_say` / `fake_silence` to
/// feed it. Call before `execute(BridgeCommand::StartSession)`.
Future<void> fakeBeginSession() =>
    RustLib.instance.api.crateApiFakeBeginSession();

/// Feed one scripted phrase (partial, then final) into the open session.
Future<void> fakeSay({required String text}) =>
    RustLib.instance.api.crateApiFakeSay(text: text);

/// Feed one scripted cumulative-silence event (milliseconds) into the open
/// session.
Future<void> fakeSilence({required BigInt elapsedMs}) =>
    RustLib.instance.api.crateApiFakeSilence(elapsedMs: elapsedMs);

@freezed
sealed class BridgeCommand with _$BridgeCommand {
  const BridgeCommand._();

  const factory BridgeCommand.startSession() = BridgeCommand_StartSession;
  const factory BridgeCommand.stopSession() = BridgeCommand_StopSession;
  const factory BridgeCommand.cancel() = BridgeCommand_Cancel;
  const factory BridgeCommand.confirmInsert() = BridgeCommand_ConfirmInsert;
  const factory BridgeCommand.reroll() = BridgeCommand_Reroll;
  const factory BridgeCommand.updatePreviewText({required String text}) =
      BridgeCommand_UpdatePreviewText;

  /// The selected scenario's style-directive text; `None` returns to
  /// the built-in default register. The engine knows nothing about
  /// scenario names.
  const factory BridgeCommand.setStyleDirective({String? directive}) =
      BridgeCommand_SetStyleDirective;

  /// Passage mode (篇章模式) as it stands now — the value the next
  /// session opens with (the engine snapshots it per session).
  const factory BridgeCommand.setPassageMode({required bool on_}) =
      BridgeCommand_SetPassageMode;

  /// History retrieval re-running a past utterance (see `RectifyText`).
  const factory BridgeCommand.rectifyText({required String rawTranscript}) =
      BridgeCommand_RectifyText;
}

/// One failed case: the engine-level error when the case never produced
/// output, else the assertion verdicts that failed.
class BridgeEvalCaseDetail {
  final String id;
  final String? error;
  final List<String> failures;

  const BridgeEvalCaseDetail({
    required this.id,
    this.error,
    required this.failures,
  });

  @override
  int get hashCode => id.hashCode ^ error.hashCode ^ failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvalCaseDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          error == other.error &&
          failures == other.failures;
}

/// One category line in the summary (label + count).
class BridgeEvalCategory {
  final String label;
  final int count;

  const BridgeEvalCategory({required this.label, required this.count});

  @override
  int get hashCode => label.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvalCategory &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          count == other.count;
}

@freezed
sealed class BridgeEvalEvent with _$BridgeEvalEvent {
  const BridgeEvalEvent._();

  /// The suite loaded and the first case is about to run.
  const factory BridgeEvalEvent.started({required int total}) =
      BridgeEvalEvent_Started;
  const factory BridgeEvalEvent.caseStarted({
    required int index,
    required int total,
    required String id,
  }) = BridgeEvalEvent_CaseStarted;
  const factory BridgeEvalEvent.caseFinished({
    required int index,
    required String id,
    required bool passed,
  }) = BridgeEvalEvent_CaseFinished;

  /// The run completed; the summary carries everything the pane paints.
  const factory BridgeEvalEvent.finished({required BridgeEvalSummary summary}) =
      BridgeEvalEvent_Finished;

  /// The run never completed (missing LLM config, an aborted run, an
  /// engine-level failure).
  const factory BridgeEvalEvent.failed({required String message}) =
      BridgeEvalEvent_Failed;
}

/// What a finished run reports: the pass rate against the recorded
/// baseline, failure counts per category, and the failed cases with
/// their machine-verdict details.
class BridgeEvalSummary {
  final int total;
  final int passed;
  final int failed;

  /// Cases that never produced output to check (engine/LLM errors) —
  /// already inside `failed`, broken out for display.
  final int execFailed;

  /// Passed share, 0.0–100.0.
  final double ratePercent;

  /// The recorded baseline (BASELINE.md beside the suite) the run
  /// compares against.
  final double baselinePercent;

  /// Which LLM actually ran the cases.
  final String model;

  /// Failure counts per category, display order (Chinese labels).
  final List<BridgeEvalCategory> categories;

  /// The failed cases only, with assertion details.
  final List<BridgeEvalCaseDetail> failedCases;

  const BridgeEvalSummary({
    required this.total,
    required this.passed,
    required this.failed,
    required this.execFailed,
    required this.ratePercent,
    required this.baselinePercent,
    required this.model,
    required this.categories,
    required this.failedCases,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      passed.hashCode ^
      failed.hashCode ^
      execFailed.hashCode ^
      ratePercent.hashCode ^
      baselinePercent.hashCode ^
      model.hashCode ^
      categories.hashCode ^
      failedCases.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvalSummary &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          passed == other.passed &&
          failed == other.failed &&
          execFailed == other.execFailed &&
          ratePercent == other.ratePercent &&
          baselinePercent == other.baselinePercent &&
          model == other.model &&
          categories == other.categories &&
          failedCases == other.failedCases;
}

@freezed
sealed class BridgeEvent with _$BridgeEvent {
  const BridgeEvent._();

  const factory BridgeEvent.sessionStateChanged({
    required BridgeSessionState from,
    required BridgeSessionState to,
  }) = BridgeEvent_SessionStateChanged;
  const factory BridgeEvent.liveTranscriptUpdated({required String text}) =
      BridgeEvent_LiveTranscriptUpdated;
  const factory BridgeEvent.paragraphMarked() = BridgeEvent_ParagraphMarked;
  const factory BridgeEvent.speechActivityChanged({required bool speaking}) =
      BridgeEvent_SpeechActivityChanged;
  const factory BridgeEvent.rectifiedTextChunk({required String delta}) =
      BridgeEvent_RectifiedTextChunk;
  const factory BridgeEvent.previewTextUpdated({required String text}) =
      BridgeEvent_PreviewTextUpdated;
  const factory BridgeEvent.textInserted({required String text}) =
      BridgeEvent_TextInserted;
  const factory BridgeEvent.error({required String message}) =
      BridgeEvent_Error;
}

/// Dart-side mirror of [`EventEnvelope`].
class BridgeEventEnvelope {
  final BigInt seq;
  final BigInt sessionId;
  final BigInt atMs;
  final BridgeEvent event;

  const BridgeEventEnvelope({
    required this.seq,
    required this.sessionId,
    required this.atMs,
    required this.event,
  });

  @override
  int get hashCode =>
      seq.hashCode ^ sessionId.hashCode ^ atMs.hashCode ^ event.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEventEnvelope &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          sessionId == other.sessionId &&
          atMs == other.atMs &&
          event == other.event;
}

/// Dart-side mirror of the `[history]` settings (保留期 / 不留存).
class BridgeHistoryConfig {
  final bool enabled;
  final BigInt retentionDays;

  const BridgeHistoryConfig({
    required this.enabled,
    required this.retentionDays,
  });

  @override
  int get hashCode => enabled.hashCode ^ retentionDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          retentionDays == other.retentionDays;
}

/// Dart-side mirror of the history store's row: one stored session.
class BridgeHistoryEntry {
  final PlatformInt64 id;

  /// Unix-epoch milliseconds, for the panel's timestamps.
  final BigInt createdAtMs;
  final String rawTranscript;
  final String rectifiedText;

  const BridgeHistoryEntry({
    required this.id,
    required this.createdAtMs,
    required this.rawTranscript,
    required this.rectifiedText,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAtMs.hashCode ^
      rawTranscript.hashCode ^
      rectifiedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAtMs == other.createdAtMs &&
          rawTranscript == other.rawTranscript &&
          rectifiedText == other.rectifiedText;
}

/// Dart-side mirror of one scenario (场景): a user-named style directive
/// from the scenario library.
class BridgeScenario {
  final String name;
  final String directive;

  const BridgeScenario({required this.name, required this.directive});

  @override
  int get hashCode => name.hashCode ^ directive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeScenario &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          directive == other.directive;
}

/// Dart-side mirror of [`SessionState`].
enum BridgeSessionState {
  idle,
  recording,
  rectifying,
  preview,
  inserted,
  cancelled,
}
