// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `global`, `token_scripts`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Global`, `SpeechSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

/// Build the engine behind the bridge with the real default microphone:
/// capture + VAD as the ASR provider (speech activity, silence semantics,
/// device-failure feedback), a scripted cycling LLM, and a recording
/// inserter. Session semantics (passage mode, silence thresholds) load
/// from the `[engine]` section of the layered config files. Idempotent: a
/// second call is a no-op.
Future<void> createEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiCreateEngine(llmResponses: llmResponses);

/// Build the engine behind the bridge with all-fake collaborators.
/// `llm_responses` become the scripted rectify responses (streamed in small
/// chunks), repeating forever — the demo host never runs dry no matter how
/// many sessions or rerolls come. Idempotent: a second call is a no-op.
Future<void> createFakeEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiCreateFakeEngine(llmResponses: llmResponses);

/// Submit a command to the engine. Returns an error only for rejected
/// commands (wrong state); asynchronous outcomes arrive on the event stream.
Future<void> execute({required BridgeCommand command}) =>
    RustLib.instance.api.crateApiExecute(command: command);

/// Current session state, for initial paint before any event arrives.
Future<BridgeSessionState> state() => RustLib.instance.api.crateApiState();

/// Everything the fake inserter received, in order (demo introspection).
Future<List<String>> insertedTexts() =>
    RustLib.instance.api.crateApiInsertedTexts();

/// Subscribe the Dart side to the engine's event stream. Each call spawns
/// an independent forwarder; dropping the Dart stream stops it.
Stream<BridgeEventEnvelope> subscribe() =>
    RustLib.instance.api.crateApiSubscribe();

/// Open the next fake ASR session and allow `fake_say` / `fake_silence` to
/// feed it. Call before `execute(BridgeCommand::StartSession)`.
Future<void> fakeBeginSession() =>
    RustLib.instance.api.crateApiFakeBeginSession();

/// Feed one scripted phrase (partial, then final) into the open session.
Future<void> fakeSay({required String text}) =>
    RustLib.instance.api.crateApiFakeSay(text: text);

/// Feed one scripted cumulative-silence event (milliseconds) into the open
/// session.
Future<void> fakeSilence({required BigInt elapsedMs}) =>
    RustLib.instance.api.crateApiFakeSilence(elapsedMs: elapsedMs);

@freezed
sealed class BridgeCommand with _$BridgeCommand {
  const BridgeCommand._();

  const factory BridgeCommand.startSession() = BridgeCommand_StartSession;
  const factory BridgeCommand.stopSession() = BridgeCommand_StopSession;
  const factory BridgeCommand.cancel() = BridgeCommand_Cancel;
  const factory BridgeCommand.confirmInsert() = BridgeCommand_ConfirmInsert;
  const factory BridgeCommand.reroll() = BridgeCommand_Reroll;
  const factory BridgeCommand.updatePreviewText({required String text}) =
      BridgeCommand_UpdatePreviewText;
  const factory BridgeCommand.setStyle({required BridgeStyle style}) =
      BridgeCommand_SetStyle;
}

@freezed
sealed class BridgeEvent with _$BridgeEvent {
  const BridgeEvent._();

  const factory BridgeEvent.sessionStateChanged({
    required BridgeSessionState from,
    required BridgeSessionState to,
  }) = BridgeEvent_SessionStateChanged;
  const factory BridgeEvent.liveTranscriptUpdated({required String text}) =
      BridgeEvent_LiveTranscriptUpdated;
  const factory BridgeEvent.paragraphMarked() = BridgeEvent_ParagraphMarked;
  const factory BridgeEvent.speechActivityChanged({required bool speaking}) =
      BridgeEvent_SpeechActivityChanged;
  const factory BridgeEvent.rectifiedTextChunk({required String delta}) =
      BridgeEvent_RectifiedTextChunk;
  const factory BridgeEvent.previewTextUpdated({required String text}) =
      BridgeEvent_PreviewTextUpdated;
  const factory BridgeEvent.textInserted({required String text}) =
      BridgeEvent_TextInserted;
  const factory BridgeEvent.error({required String message}) =
      BridgeEvent_Error;
}

/// Dart-side mirror of [`EventEnvelope`].
class BridgeEventEnvelope {
  final BigInt seq;
  final BigInt sessionId;
  final BigInt atMs;
  final BridgeEvent event;

  const BridgeEventEnvelope({
    required this.seq,
    required this.sessionId,
    required this.atMs,
    required this.event,
  });

  @override
  int get hashCode =>
      seq.hashCode ^ sessionId.hashCode ^ atMs.hashCode ^ event.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEventEnvelope &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          sessionId == other.sessionId &&
          atMs == other.atMs &&
          event == other.event;
}

/// Dart-side mirror of [`SessionState`].
enum BridgeSessionState {
  idle,
  recording,
  rectifying,
  preview,
  inserted,
  cancelled,
}

/// Dart-side mirror of [`Style`].
enum BridgeStyle { generalWritten, prompt, formalDocument }
