// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `asr_view`, `bridge_key`, `global`, `history_config_err`, `launch_editor`, `llm_view`, `open_fake_feed`, `token_scripts`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Global`, `InserterSlot`, `SpeechSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Build the engine behind the bridge with the real default microphone
/// and, when the `[asr]` config carries credentials, the configured
/// provider's cloud adapter streaming real transcripts (see
/// `engine_factory::asr_provider` for the dispatch and its error
/// rules). Without credentials the mic+VAD provider keeps the session
/// semantics (speech activity, silence, device failure). The rectify
/// LLM is the real OpenAI-compatible client when
/// `[llm]` yields a key; the scripted demo LLM otherwise — but that
/// combination is refused under a real ASR key (see `engine_factory`).
/// Insertion is the production inserter (clipboard paste with restore, or
/// typing per the `[insertion]` config). Session semantics load from the
/// `[engine]` section of the layered config files. Idempotent: a second
/// call is a no-op.
Future<void> createEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiCreateEngine(llmResponses: llmResponses);

/// Build the engine behind the bridge with all-fake collaborators.
/// `llm_responses` become the scripted rectify responses (streamed in small
/// chunks), repeating forever — the demo host never runs dry no matter how
/// many sessions or rerolls come. Idempotent: a second call is a no-op.
Future<void> createFakeEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiCreateFakeEngine(llmResponses: llmResponses);

/// Submit a command to the engine. Returns an error only for rejected
/// commands (wrong state); asynchronous outcomes arrive on the event stream.
Future<void> execute({required BridgeCommand command}) =>
    RustLib.instance.api.crateApiExecute(command: command);

/// Current session state, for initial paint before any event arrives.
Future<BridgeSessionState> state() => RustLib.instance.api.crateApiState();

/// Passage mode as it stands now (config-seeded, runtime-switched) —
/// what the quick panel's toggle paints and what the next session opens
/// with.
Future<bool> passageMode() => RustLib.instance.api.crateApiPassageMode();

/// Hand the keyboard back to the remembered target window — the quick
/// panel's own close path. Self-guarded on the inserter side: a foreign
/// foreground (or no remembered target) is left alone, exactly like the
/// cancel-path restore. No-op on the fake engine.
Future<void> restoreFocus() => RustLib.instance.api.crateApiRestoreFocus();

/// The hotword dictionary as it stands now, in file order — the quick
/// panel's term chips. File-level, engine-independent (the engine
/// re-reads the file when the next session opens, which is what makes a
/// quick-added term live for that session).
Future<List<String>> termsList() => RustLib.instance.api.crateApiTermsList();

/// Quick-add one term to the dictionary (idempotent; blank rejected).
/// See [`spokenrectifier_config::terms::append_term`] for the placement
/// and repair rules.
Future<void> appendTerm({required String term}) =>
    RustLib.instance.api.crateApiAppendTerm(term: term);

/// Remove a term from the dictionary (a no-op when absent).
Future<void> removeTerm({required String term}) =>
    RustLib.instance.api.crateApiRemoveTerm(term: term);

/// The scenario library (场景库): user-named style directives from the
/// app-owned `spokenrectifier-scenarios.toml`. A missing or corrupt file
/// reads as an empty library — this never errors and never writes. The
/// shell paints its pickers from the list and resolves the selected
/// entry's directive text itself (selection lives app-side, never
/// persisted; ADR-0004).
Future<List<BridgeScenario>> scenarios() =>
    RustLib.instance.api.crateApiScenarios();

/// Save the whole scenario library — the settings editor's model,
/// wholesale — into the file the loader resolves (created in the app's
/// settings home when no library exists yet). File-level and
/// engine-independent like [`scenarios`]: the pickers re-read the library
/// after a save; the selected scenario's directive rides the next
/// `SetStyleDirective` as usual. Only ever runs on a user action (the
/// editor's add/edit/delete), never on load.
Future<void> saveScenarios({required List<BridgeScenario> scenarios}) =>
    RustLib.instance.api.crateApiSaveScenarios(scenarios: scenarios);

/// The global directive (全局指令, ticket 22): the single `directive` key
/// from the app-owned `spokenrectifier-global.toml` — a companion file of
/// the scenario library's, so a library rewrite cannot lose it. A
/// missing, corrupt, or blank file reads as `None` (unset); this never
/// errors and never writes. The shell pushes the text at the engine via
/// `SetGlobalDirective` and repaints its preview from this same read.
Future<String?> globalDirective() =>
    RustLib.instance.api.crateApiGlobalDirective();

/// Save the global directive into the file the loader resolves (created
/// in the app's settings home when none exists yet). `None` and blank
/// text both write the canonical unset form — clearing the field and
/// saving is the off switch. File-level and engine-independent like
/// [`global_directive`]: the main window re-reads the file and pushes the
/// fresh text at the engine (`SetGlobalDirective`) on the
/// global-changed event. Only ever runs on a user action.
Future<void> saveGlobalDirective({String? directive}) =>
    RustLib.instance.api.crateApiSaveGlobalDirective(directive: directive);

/// Everything the fake inserter received, in order (demo introspection).
/// The production inserter does not record; insertion outcomes arrive on
/// the event stream instead (`TextInserted` / `Error`).
Future<List<String>> insertedTexts() =>
    RustLib.instance.api.crateApiInsertedTexts();

/// The most recent stored sessions, newest first — the history panel's
/// content. Empty in the keep-nothing mode (and on the fake engine).
Future<List<BridgeHistoryEntry>> historyList() =>
    RustLib.instance.api.crateApiHistoryList();

/// Remove every stored session — the tray's one-click clear. A no-op in
/// the keep-nothing mode.
Future<void> historyClear() => RustLib.instance.api.crateApiHistoryClear();

/// The effective `[history]` settings from the layer files — the
/// settings window's history pane initial paint.
Future<BridgeHistoryConfig> historyConfig() =>
    RustLib.instance.api.crateApiHistoryConfig();

/// Write new `[history]` settings and apply them to the live store at
/// once (the settings window's 保留期 / 不留存 controls): the file edit
/// is section-preserving in the layer that owns the effective values,
/// and the store adopts the new config immediately — a tightened
/// retention sweeps at once, keep-nothing wipes, and turning it back on
/// resumes recording. Returns the re-read effective config.
Future<BridgeHistoryConfig> setHistoryConfig({
  required bool enabled,
  required BigInt retentionDays,
}) => RustLib.instance.api.crateApiSetHistoryConfig(
  enabled: enabled,
  retentionDays: retentionDays,
);

/// The effective `[asr]` and `[llm]` connections from the layer files —
/// the connection domain's initial paint. File-level and
/// engine-independent: the engine adopts the config at its creation,
/// and a save re-adopts it at once via [`apply_connection_configs`] —
/// next session (ASR) / next attempt (LLM), no restart (ADR-0010). The
/// fidelity-eval run builds its own engine per run, unaffected.
Future<BridgeConnection> connectionConfig() =>
    RustLib.instance.api.crateApiConnectionConfig();

/// Write the editor's whole `[asr]` card back into the layer files (see
/// `save_asr_connection` for the placement and preservation rules —
/// common fields plus every vendor sub-section, every secret to the
/// local layer only) and return the re-read view — the file's truth,
/// not the ask.
Future<BridgeAsrConnection> setAsrConnection({required BridgeAsrEdit edit}) =>
    RustLib.instance.api.crateApiSetAsrConnection(edit: edit);

/// The settings pane's live endpoint preview: the WebSocket URL the
/// form's current fields resolve to, recomputed while the user types
/// or switches the provider chip — the same [`AsrConfig::endpoint`]
/// derivation the loaded view previews with, so there is exactly one.
Future<String?> asrEndpointPreview({
  required String provider,
  required String model,
  String? baseUrl,
  String? workspaceId,
  required String region,
}) => RustLib.instance.api.crateApiAsrEndpointPreview(
  provider: provider,
  model: model,
  baseUrl: baseUrl,
  workspaceId: workspaceId,
  region: region,
);

/// Write the editor's `[llm]` model back into the layer files (see
/// `save_llm_connection`) and return the re-read view.
Future<BridgeLlmConnection> setLlmConnection({
  required String vendor,
  required String baseUrl,
  required String model,
  required BridgeKeyEdit apiKey,
}) => RustLib.instance.api.crateApiSetLlmConnection(
  vendor: vendor,
  baseUrl: baseUrl,
  model: model,
  apiKey: apiKey,
);

/// Adopt the saved `[asr]` and `[llm]` connections into the live engine at
/// once (ADR-0010): the settings window calls this right after a save
/// lands, so the next session opens with the new ASR provider and the next
/// rectify attempt with the new LLM — no restart. Re-reads the layer
/// files and rebuilds both collaborators through the same factory the
/// startup path uses (mic-only fallback included: clearing the provider's
/// credentials really does drop back to mic+VAD at runtime).
///
/// The rebuild happens before any handover, so any refusal (an incomplete
/// credential set, an unadapted provider, the demo-mode LLM that has no
/// runtime script — all tested in `engine_factory`) returns `Err` and
/// keeps BOTH previous collaborators running; the files stay saved either
/// way, so the next launch adopts them regardless. The swap semantics are
/// locked by the engine's `live_swap` tests. A no-op on the fake engine
/// (tests and demos hold no production collaborators to swap).
Future<void> applyConnectionConfigs() =>
    RustLib.instance.api.crateApiApplyConnectionConfigs();

/// Rename a term in the dictionary, in place (the settings editor's 改;
/// the quick panel's quick-add and quick-remove stay the same calls).
/// See [`spokenrectifier_config::terms::update_term`] for the placement
/// and collision rules.
Future<void> updateTerm({required String old, required String new_}) =>
    RustLib.instance.api.crateApiUpdateTerm(old: old, new_: new_);

/// The advanced domain's one read: the session and insertion latency
/// parameters, effective right now (the editable form's initial paint).
Future<BridgeAdvancedConfig> advancedConfig() =>
    RustLib.instance.api.crateApiAdvancedConfig();

/// Write the form's `[engine]` model (passage mode + the three timings)
/// into the layer files and hand it to the live engine at once
/// (ADR-0007, revised): both runtime commands adopt the saved values
/// immediately, and each session snapshots what it opens with — so the
/// save applies from the NEXT session on, while the file stays the
/// truth across launches. The quick panel's passage toggle stays the
/// runtime-only quick switch; this one persists. Returns the re-read
/// view.
Future<BridgeEngineTiming> setEngineSettings({
  required bool passageMode,
  required BigInt paragraphSilenceMs,
  required BigInt sessionEndSilenceMs,
  required BigInt rectifyTimeoutMs,
}) => RustLib.instance.api.crateApiSetEngineSettings(
  passageMode: passageMode,
  paragraphSilenceMs: paragraphSilenceMs,
  sessionEndSilenceMs: sessionEndSilenceMs,
  rectifyTimeoutMs: rectifyTimeoutMs,
);

/// Write the form's `[insertion]` model into the layer files and apply
/// it to the live inserter at once (ADR-0007, 2026-08-28 revision):
/// insertion is discrete per-confirm, so the swap is true real-time —
/// the very next ConfirmInsert runs with the new mode and pacing. A
/// no-op apply on the fake engine (tests and demos hold no target
/// window); the file write still lands. Returns the re-read view.
Future<BridgeInsertionTiming> setInsertionTiming({
  required String mode,
  required BigInt focusSettleMs,
  required BigInt pasteSettleMs,
  required BigInt typingDelayMs,
}) => RustLib.instance.api.crateApiSetInsertionTiming(
  mode: mode,
  focusSettleMs: focusSettleMs,
  pasteSettleMs: pasteSettleMs,
  typingDelayMs: typingDelayMs,
);

/// The about pane's one read (version, license, repository).
Future<BridgeAbout> about() => RustLib.instance.api.crateApiAbout();

/// Start one fidelity-eval run in the background — the settings window's
/// manual entry. Every case rides the event stream; the run ends with
/// `Finished` or `Failed`. Dropping the Dart listener (window closed,
/// pane cancelled) aborts the run at the next case boundary. Only one
/// run at a time: a second call while running is an error.
///
/// The run builds its own engine instance (noop inserter, no history
/// recorder, the suite's fixed term list) against the real configured
/// LLM — the app's live engine is never touched, so the eval neither
/// inserts text nor pollutes history (the sr-eval seam, in-process).
Stream<BridgeEvalEvent> startFidelityEval() =>
    RustLib.instance.api.crateApiStartFidelityEval();

/// Open the shared config file in the system text editor — the tray's
/// settings entry. Creates a commented stub first when no config file
/// exists yet (see `settings::ensure_shared_config` for where). Returns
/// the path that was opened.
Future<String> openConfigFile() =>
    RustLib.instance.api.crateApiOpenConfigFile();

/// Subscribe the Dart side to the engine's event stream. Each call spawns
/// an independent forwarder; dropping the Dart stream stops it.
Stream<BridgeEventEnvelope> subscribe() =>
    RustLib.instance.api.crateApiSubscribe();

/// Open the next fake ASR session and allow `fake_say` / `fake_silence` to
/// feed it. Call before `execute(BridgeCommand::StartSession)`.
Future<void> fakeBeginSession() =>
    RustLib.instance.api.crateApiFakeBeginSession();

/// Feed one scripted phrase (partial, then final) into the open session.
Future<void> fakeSay({required String text}) =>
    RustLib.instance.api.crateApiFakeSay(text: text);

/// Feed one scripted cumulative-silence event (milliseconds) into the open
/// session.
Future<void> fakeSilence({required BigInt elapsedMs}) =>
    RustLib.instance.api.crateApiFakeSilence(elapsedMs: elapsedMs);

/// What the about pane paints. The version is the app crate's manifest
/// (kept in step with the Flutter `pubspec.yaml` — bump both together).
class BridgeAbout {
  final String version;
  final String license;

  /// The public repository; absent until the open-source packaging
  /// (ticket 11) names one.
  final String? repoUrl;

  const BridgeAbout({
    required this.version,
    required this.license,
    this.repoUrl,
  });

  @override
  int get hashCode => version.hashCode ^ license.hashCode ^ repoUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAbout &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          license == other.license &&
          repoUrl == other.repoUrl;
}

/// Both timing cards in one read.
class BridgeAdvancedConfig {
  final BridgeEngineTiming engine;
  final BridgeInsertionTiming insertion;

  const BridgeAdvancedConfig({required this.engine, required this.insertion});

  @override
  int get hashCode => engine.hashCode ^ insertion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAdvancedConfig &&
          runtimeType == other.runtimeType &&
          engine == other.engine &&
          insertion == other.insertion;
}

/// `[asr.aliyun]` for the pane.
class BridgeAsrAliyun {
  final String? workspaceId;
  final String region;

  const BridgeAsrAliyun({this.workspaceId, required this.region});

  @override
  int get hashCode => workspaceId.hashCode ^ region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAliyun &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          region == other.region;
}

class BridgeAsrAliyunEdit {
  final String? workspaceId;
  final String region;

  const BridgeAsrAliyunEdit({this.workspaceId, required this.region});

  @override
  int get hashCode => workspaceId.hashCode ^ region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAliyunEdit &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          region == other.region;
}

/// `[asr.azure]` for the pane (adapter not scheduled).
class BridgeAsrAzure {
  final String? region;
  final String? endpointId;

  const BridgeAsrAzure({this.region, this.endpointId});

  @override
  int get hashCode => region.hashCode ^ endpointId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAzure &&
          runtimeType == other.runtimeType &&
          region == other.region &&
          endpointId == other.endpointId;
}

class BridgeAsrAzureEdit {
  final String? region;
  final String? endpointId;

  const BridgeAsrAzureEdit({this.region, this.endpointId});

  @override
  int get hashCode => region.hashCode ^ endpointId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAzureEdit &&
          runtimeType == other.runtimeType &&
          region == other.region &&
          endpointId == other.endpointId;
}

/// The effective `[asr]` connection as the settings pane paints it: the
/// common segment's folded fields, every vendor sub-section (the pane
/// renders the active one), the resolved endpoint (a read-only preview;
/// `None` for providers without an adapter yet), and each secret's
/// placement.
class BridgeAsrConnection {
  /// `aliyun` / `volcengine` / `tencent` / `openai` / `azure`.
  final String provider;
  final String model;
  final String language;
  final String? baseUrl;

  /// The WebSocket URL the current fields resolve to.
  final String? endpoint;

  /// The common Bearer key pair (the active provider's, when its
  /// family is the Bearer one).
  final BridgeKeyStatus key;
  final BridgeAsrAliyun aliyun;
  final BridgeAsrVolcengine volcengine;
  final BridgeAsrTencent tencent;
  final BridgeAsrAzure azure;

  const BridgeAsrConnection({
    required this.provider,
    required this.model,
    required this.language,
    this.baseUrl,
    this.endpoint,
    required this.key,
    required this.aliyun,
    required this.volcengine,
    required this.tencent,
    required this.azure,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      model.hashCode ^
      language.hashCode ^
      baseUrl.hashCode ^
      endpoint.hashCode ^
      key.hashCode ^
      aliyun.hashCode ^
      volcengine.hashCode ^
      tencent.hashCode ^
      azure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrConnection &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          model == other.model &&
          language == other.language &&
          baseUrl == other.baseUrl &&
          endpoint == other.endpoint &&
          key == other.key &&
          aliyun == other.aliyun &&
          volcengine == other.volcengine &&
          tencent == other.tencent &&
          azure == other.azure;
}

/// The editor's whole `[asr]` card, mirroring the schema's
/// [`AsrConnectionEdit`]: common fields plus every vendor sub-section
/// (a provider switch never clears another vendor's fields).
class BridgeAsrEdit {
  final String provider;
  final String model;
  final String language;
  final String? baseUrl;
  final BridgeKeyEdit apiKey;
  final BridgeAsrAliyunEdit aliyun;
  final BridgeAsrVolcengineEdit volcengine;
  final BridgeAsrTencentEdit tencent;
  final BridgeAsrAzureEdit azure;

  const BridgeAsrEdit({
    required this.provider,
    required this.model,
    required this.language,
    this.baseUrl,
    required this.apiKey,
    required this.aliyun,
    required this.volcengine,
    required this.tencent,
    required this.azure,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      model.hashCode ^
      language.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      aliyun.hashCode ^
      volcengine.hashCode ^
      tencent.hashCode ^
      azure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrEdit &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          model == other.model &&
          language == other.language &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          aliyun == other.aliyun &&
          volcengine == other.volcengine &&
          tencent == other.tencent &&
          azure == other.azure;
}

/// `[asr.tencent]` for the pane (adapter: ticket 25).
class BridgeAsrTencent {
  final String? appId;
  final BridgeKeyStatus secretId;
  final BridgeKeyStatus secretKey;

  const BridgeAsrTencent({
    this.appId,
    required this.secretId,
    required this.secretKey,
  });

  @override
  int get hashCode => appId.hashCode ^ secretId.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrTencent &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          secretId == other.secretId &&
          secretKey == other.secretKey;
}

class BridgeAsrTencentEdit {
  final String? appId;
  final BridgeKeyEdit secretId;
  final BridgeKeyEdit secretKey;

  const BridgeAsrTencentEdit({
    this.appId,
    required this.secretId,
    required this.secretKey,
  });

  @override
  int get hashCode => appId.hashCode ^ secretId.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrTencentEdit &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          secretId == other.secretId &&
          secretKey == other.secretKey;
}

/// `[asr.volcengine]` for the pane; the access token echoes per the
/// diff-echo key block.
class BridgeAsrVolcengine {
  final String? appId;
  final String resourceId;
  final BridgeKeyStatus accessKey;

  const BridgeAsrVolcengine({
    this.appId,
    required this.resourceId,
    required this.accessKey,
  });

  @override
  int get hashCode => appId.hashCode ^ resourceId.hashCode ^ accessKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrVolcengine &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          resourceId == other.resourceId &&
          accessKey == other.accessKey;
}

class BridgeAsrVolcengineEdit {
  final String? appId;
  final String resourceId;
  final BridgeKeyEdit accessKey;

  const BridgeAsrVolcengineEdit({
    this.appId,
    required this.resourceId,
    required this.accessKey,
  });

  @override
  int get hashCode => appId.hashCode ^ resourceId.hashCode ^ accessKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrVolcengineEdit &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          resourceId == other.resourceId &&
          accessKey == other.accessKey;
}

@freezed
sealed class BridgeCommand with _$BridgeCommand {
  const BridgeCommand._();

  const factory BridgeCommand.startSession() = BridgeCommand_StartSession;
  const factory BridgeCommand.stopSession() = BridgeCommand_StopSession;
  const factory BridgeCommand.cancel() = BridgeCommand_Cancel;
  const factory BridgeCommand.confirmInsert() = BridgeCommand_ConfirmInsert;
  const factory BridgeCommand.reroll() = BridgeCommand_Reroll;
  const factory BridgeCommand.updatePreviewText({required String text}) =
      BridgeCommand_UpdatePreviewText;

  /// The selected scenario's style-directive text; `None` returns to
  /// the built-in default register. The engine knows nothing about
  /// scenario names.
  const factory BridgeCommand.setStyleDirective({String? directive}) =
      BridgeCommand_SetStyleDirective;

  /// The global directive's text (ticket 22; the engine knows nothing
  /// about where it is stored); `None` unsets it. A live value read at
  /// every request assembly, never pinned per session.
  const factory BridgeCommand.setGlobalDirective({String? directive}) =
      BridgeCommand_SetGlobalDirective;

  /// Passage mode (篇章模式) as it stands now — the value the next
  /// session opens with (the engine snapshots it per session).
  const factory BridgeCommand.setPassageMode({required bool on_}) =
      BridgeCommand_SetPassageMode;

  /// The latency timings as they stand now — the values the next
  /// session opens with (the engine snapshots them per session). The
  /// settings window's advanced form sends this right after the file
  /// write, so the live engine adopts the saved values at once.
  const factory BridgeCommand.setEngineTimings({
    required BigInt paragraphSilenceMs,
    required BigInt sessionEndSilenceMs,
    required BigInt rectifyTimeoutMs,
  }) = BridgeCommand_SetEngineTimings;

  /// History retrieval re-running a past utterance (see `RectifyText`).
  /// `style_override` optionally pins a one-time scenario directive for
  /// that session alone (ticket 23); `None` runs under the live
  /// selection.
  const factory BridgeCommand.rectifyText({
    required String rawTranscript,
    String? styleOverride,
  }) = BridgeCommand_RectifyText;
}

/// Both connections in one read.
class BridgeConnection {
  final BridgeAsrConnection asr;
  final BridgeLlmConnection llm;

  const BridgeConnection({required this.asr, required this.llm});

  @override
  int get hashCode => asr.hashCode ^ llm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConnection &&
          runtimeType == other.runtimeType &&
          asr == other.asr &&
          llm == other.llm;
}

/// The effective `[engine]` timings as the advanced pane paints them
/// (read-only; see ADR-0007 for why they stay file-only).
class BridgeEngineTiming {
  final bool passageMode;
  final BigInt paragraphSilenceMs;
  final BigInt sessionEndSilenceMs;
  final BigInt rectifyTimeoutMs;

  const BridgeEngineTiming({
    required this.passageMode,
    required this.paragraphSilenceMs,
    required this.sessionEndSilenceMs,
    required this.rectifyTimeoutMs,
  });

  @override
  int get hashCode =>
      passageMode.hashCode ^
      paragraphSilenceMs.hashCode ^
      sessionEndSilenceMs.hashCode ^
      rectifyTimeoutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEngineTiming &&
          runtimeType == other.runtimeType &&
          passageMode == other.passageMode &&
          paragraphSilenceMs == other.paragraphSilenceMs &&
          sessionEndSilenceMs == other.sessionEndSilenceMs &&
          rectifyTimeoutMs == other.rectifyTimeoutMs;
}

/// One failed case: the engine-level error when the case never produced
/// output, else the assertion verdicts that failed.
class BridgeEvalCaseDetail {
  final String id;
  final String? error;
  final List<String> failures;

  const BridgeEvalCaseDetail({
    required this.id,
    this.error,
    required this.failures,
  });

  @override
  int get hashCode => id.hashCode ^ error.hashCode ^ failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvalCaseDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          error == other.error &&
          failures == other.failures;
}

/// One category line in the summary (label + count).
class BridgeEvalCategory {
  final String label;
  final int count;

  const BridgeEvalCategory({required this.label, required this.count});

  @override
  int get hashCode => label.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvalCategory &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          count == other.count;
}

@freezed
sealed class BridgeEvalEvent with _$BridgeEvalEvent {
  const BridgeEvalEvent._();

  /// The suite loaded and the first case is about to run.
  const factory BridgeEvalEvent.started({required int total}) =
      BridgeEvalEvent_Started;
  const factory BridgeEvalEvent.caseStarted({
    required int index,
    required int total,
    required String id,
  }) = BridgeEvalEvent_CaseStarted;
  const factory BridgeEvalEvent.caseFinished({
    required int index,
    required String id,
    required bool passed,
  }) = BridgeEvalEvent_CaseFinished;

  /// The run completed; the summary carries everything the pane paints.
  const factory BridgeEvalEvent.finished({required BridgeEvalSummary summary}) =
      BridgeEvalEvent_Finished;

  /// The run never completed (missing LLM config, an aborted run, an
  /// engine-level failure).
  const factory BridgeEvalEvent.failed({required String message}) =
      BridgeEvalEvent_Failed;
}

/// What a finished run reports: the pass rate against the recorded
/// baseline, failure counts per category, and the failed cases with
/// their machine-verdict details.
class BridgeEvalSummary {
  final int total;
  final int passed;
  final int failed;

  /// Cases that never produced output to check (engine/LLM errors) —
  /// already inside `failed`, broken out for display.
  final int execFailed;

  /// Passed share, 0.0–100.0.
  final double ratePercent;

  /// The recorded baseline (BASELINE.md beside the suite) the run
  /// compares against.
  final double baselinePercent;

  /// Which LLM actually ran the cases.
  final String model;

  /// Failure counts per category, display order (Chinese labels).
  final List<BridgeEvalCategory> categories;

  /// The failed cases only, with assertion details.
  final List<BridgeEvalCaseDetail> failedCases;

  const BridgeEvalSummary({
    required this.total,
    required this.passed,
    required this.failed,
    required this.execFailed,
    required this.ratePercent,
    required this.baselinePercent,
    required this.model,
    required this.categories,
    required this.failedCases,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      passed.hashCode ^
      failed.hashCode ^
      execFailed.hashCode ^
      ratePercent.hashCode ^
      baselinePercent.hashCode ^
      model.hashCode ^
      categories.hashCode ^
      failedCases.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvalSummary &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          passed == other.passed &&
          failed == other.failed &&
          execFailed == other.execFailed &&
          ratePercent == other.ratePercent &&
          baselinePercent == other.baselinePercent &&
          model == other.model &&
          categories == other.categories &&
          failedCases == other.failedCases;
}

@freezed
sealed class BridgeEvent with _$BridgeEvent {
  const BridgeEvent._();

  const factory BridgeEvent.sessionStateChanged({
    required BridgeSessionState from,
    required BridgeSessionState to,
  }) = BridgeEvent_SessionStateChanged;
  const factory BridgeEvent.liveTranscriptUpdated({required String text}) =
      BridgeEvent_LiveTranscriptUpdated;
  const factory BridgeEvent.paragraphMarked() = BridgeEvent_ParagraphMarked;
  const factory BridgeEvent.speechActivityChanged({required bool speaking}) =
      BridgeEvent_SpeechActivityChanged;
  const factory BridgeEvent.rectifiedTextChunk({required String delta}) =
      BridgeEvent_RectifiedTextChunk;
  const factory BridgeEvent.previewTextUpdated({required String text}) =
      BridgeEvent_PreviewTextUpdated;
  const factory BridgeEvent.textInserted({required String text}) =
      BridgeEvent_TextInserted;
  const factory BridgeEvent.error({required String message}) =
      BridgeEvent_Error;
}

/// Dart-side mirror of [`EventEnvelope`].
class BridgeEventEnvelope {
  final BigInt seq;
  final BigInt sessionId;
  final BigInt atMs;
  final BridgeEvent event;

  const BridgeEventEnvelope({
    required this.seq,
    required this.sessionId,
    required this.atMs,
    required this.event,
  });

  @override
  int get hashCode =>
      seq.hashCode ^ sessionId.hashCode ^ atMs.hashCode ^ event.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEventEnvelope &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          sessionId == other.sessionId &&
          atMs == other.atMs &&
          event == other.event;
}

/// Dart-side mirror of the `[history]` settings (保留期 / 不留存).
class BridgeHistoryConfig {
  final bool enabled;
  final BigInt retentionDays;

  const BridgeHistoryConfig({
    required this.enabled,
    required this.retentionDays,
  });

  @override
  int get hashCode => enabled.hashCode ^ retentionDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          retentionDays == other.retentionDays;
}

/// Dart-side mirror of the history store's row: one stored session.
class BridgeHistoryEntry {
  final PlatformInt64 id;

  /// Unix-epoch milliseconds, for the panel's timestamps.
  final BigInt createdAtMs;
  final String rawTranscript;
  final String rectifiedText;

  const BridgeHistoryEntry({
    required this.id,
    required this.createdAtMs,
    required this.rawTranscript,
    required this.rectifiedText,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAtMs.hashCode ^
      rawTranscript.hashCode ^
      rectifiedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAtMs == other.createdAtMs &&
          rawTranscript == other.rawTranscript &&
          rectifiedText == other.rectifiedText;
}

/// The effective `[insertion]` timings as the advanced pane paints them.
class BridgeInsertionTiming {
  /// `paste` or `typing`.
  final String mode;
  final BigInt focusSettleMs;
  final BigInt pasteSettleMs;
  final BigInt typingDelayMs;

  const BridgeInsertionTiming({
    required this.mode,
    required this.focusSettleMs,
    required this.pasteSettleMs,
    required this.typingDelayMs,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      focusSettleMs.hashCode ^
      pasteSettleMs.hashCode ^
      typingDelayMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInsertionTiming &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          focusSettleMs == other.focusSettleMs &&
          pasteSettleMs == other.pasteSettleMs &&
          typingDelayMs == other.typingDelayMs;
}

@freezed
sealed class BridgeKeyEdit with _$BridgeKeyEdit {
  const BridgeKeyEdit._();

  const factory BridgeKeyEdit.keep() = BridgeKeyEdit_Keep;
  const factory BridgeKeyEdit.clear() = BridgeKeyEdit_Clear;
  const factory BridgeKeyEdit.set_(String field0) = BridgeKeyEdit_Set;
}

@freezed
sealed class BridgeKeyStatus with _$BridgeKeyStatus {
  const BridgeKeyStatus._();

  const factory BridgeKeyStatus.unset() = BridgeKeyStatus_Unset;

  /// The stored key (from the local layer only — the loader's
  /// shared-file guard makes that the sole source).
  const factory BridgeKeyStatus.inLocalFile(String field0) =
      BridgeKeyStatus_InLocalFile;
  const factory BridgeKeyStatus.fromEnv(String field0) =
      BridgeKeyStatus_FromEnv;
}

/// The effective `[llm]` connection as the settings pane paints it.
/// `key` is the ACTIVE vendor's resolved pair; `keys` carries every
/// vendor's — a key authenticates exactly one vendor, so the pane
/// re-binds its key block per vendor chip and a switch never shows
/// another vendor's key (ADR-0011).
class BridgeLlmConnection {
  final String vendor;
  final String baseUrl;
  final String model;
  final BridgeKeyStatus key;
  final List<BridgeLlmVendorKey> keys;

  const BridgeLlmConnection({
    required this.vendor,
    required this.baseUrl,
    required this.model,
    required this.key,
    required this.keys,
  });

  @override
  int get hashCode =>
      vendor.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      key.hashCode ^
      keys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLlmConnection &&
          runtimeType == other.runtimeType &&
          vendor == other.vendor &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          key == other.key &&
          keys == other.keys;
}

/// One vendor's resolved key pair, for the pane's per-vendor key block.
class BridgeLlmVendorKey {
  final String vendor;
  final BridgeKeyStatus key;

  const BridgeLlmVendorKey({required this.vendor, required this.key});

  @override
  int get hashCode => vendor.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLlmVendorKey &&
          runtimeType == other.runtimeType &&
          vendor == other.vendor &&
          key == other.key;
}

/// Dart-side mirror of one scenario (场景): a user-named style directive
/// from the scenario library.
class BridgeScenario {
  final String name;
  final String directive;

  const BridgeScenario({required this.name, required this.directive});

  @override
  int get hashCode => name.hashCode ^ directive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeScenario &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          directive == other.directive;
}

/// Dart-side mirror of [`SessionState`].
enum BridgeSessionState {
  idle,
  recording,
  rectifying,
  preview,
  inserted,
  cancelled,
}
