// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<BridgeEvalEvent> dco_decode_StreamSink_bridge_eval_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeEventEnvelope>
  dco_decode_StreamSink_bridge_event_envelope_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeAsrEdit dco_decode_box_autoadd_bridge_asr_edit(dynamic raw);

  @protected
  BridgeCommand dco_decode_box_autoadd_bridge_command(dynamic raw);

  @protected
  BridgeEvalSummary dco_decode_box_autoadd_bridge_eval_summary(dynamic raw);

  @protected
  BridgeHistoryFilter dco_decode_box_autoadd_bridge_history_filter(dynamic raw);

  @protected
  BridgeLlmEdit dco_decode_box_autoadd_bridge_llm_edit(dynamic raw);

  @protected
  BridgeRectifyBehavior dco_decode_box_autoadd_bridge_rectify_behavior(
    dynamic raw,
  );

  @protected
  BridgeSessionStyle dco_decode_box_autoadd_bridge_session_style(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  BridgeAbout dco_decode_bridge_about(dynamic raw);

  @protected
  BridgeAdvancedConfig dco_decode_bridge_advanced_config(dynamic raw);

  @protected
  BridgeAsrAliyun dco_decode_bridge_asr_aliyun(dynamic raw);

  @protected
  BridgeAsrAliyunEdit dco_decode_bridge_asr_aliyun_edit(dynamic raw);

  @protected
  BridgeAsrAzure dco_decode_bridge_asr_azure(dynamic raw);

  @protected
  BridgeAsrAzureEdit dco_decode_bridge_asr_azure_edit(dynamic raw);

  @protected
  BridgeAsrConnection dco_decode_bridge_asr_connection(dynamic raw);

  @protected
  BridgeAsrEdit dco_decode_bridge_asr_edit(dynamic raw);

  @protected
  BridgeAsrTencent dco_decode_bridge_asr_tencent(dynamic raw);

  @protected
  BridgeAsrTencentEdit dco_decode_bridge_asr_tencent_edit(dynamic raw);

  @protected
  BridgeAsrVolcengine dco_decode_bridge_asr_volcengine(dynamic raw);

  @protected
  BridgeAsrVolcengineEdit dco_decode_bridge_asr_volcengine_edit(dynamic raw);

  @protected
  BridgeCommand dco_decode_bridge_command(dynamic raw);

  @protected
  BridgeConnection dco_decode_bridge_connection(dynamic raw);

  @protected
  BridgeEngineTiming dco_decode_bridge_engine_timing(dynamic raw);

  @protected
  BridgeEvalCaseDetail dco_decode_bridge_eval_case_detail(dynamic raw);

  @protected
  BridgeEvalCategory dco_decode_bridge_eval_category(dynamic raw);

  @protected
  BridgeEvalEvent dco_decode_bridge_eval_event(dynamic raw);

  @protected
  BridgeEvalSummary dco_decode_bridge_eval_summary(dynamic raw);

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw);

  @protected
  BridgeEventEnvelope dco_decode_bridge_event_envelope(dynamic raw);

  @protected
  BridgeHistoryConfig dco_decode_bridge_history_config(dynamic raw);

  @protected
  BridgeHistoryEntry dco_decode_bridge_history_entry(dynamic raw);

  @protected
  BridgeHistoryFilter dco_decode_bridge_history_filter(dynamic raw);

  @protected
  BridgeInsertionTiming dco_decode_bridge_insertion_timing(dynamic raw);

  @protected
  BridgeKeyEdit dco_decode_bridge_key_edit(dynamic raw);

  @protected
  BridgeKeyStatus dco_decode_bridge_key_status(dynamic raw);

  @protected
  BridgeLlmConnection dco_decode_bridge_llm_connection(dynamic raw);

  @protected
  BridgeLlmEdit dco_decode_bridge_llm_edit(dynamic raw);

  @protected
  BridgeLlmPreset dco_decode_bridge_llm_preset(dynamic raw);

  @protected
  BridgeLlmVendorKey dco_decode_bridge_llm_vendor_key(dynamic raw);

  @protected
  BridgePlaceholderFill dco_decode_bridge_placeholder_fill(dynamic raw);

  @protected
  BridgePrefillRow dco_decode_bridge_prefill_row(dynamic raw);

  @protected
  BridgeRectifyBehavior dco_decode_bridge_rectify_behavior(dynamic raw);

  @protected
  BridgeScenario dco_decode_bridge_scenario(dynamic raw);

  @protected
  BridgeSessionState dco_decode_bridge_session_state(dynamic raw);

  @protected
  BridgeSessionStyle dco_decode_bridge_session_style(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeEvalCaseDetail> dco_decode_list_bridge_eval_case_detail(
    dynamic raw,
  );

  @protected
  List<BridgeEvalCategory> dco_decode_list_bridge_eval_category(dynamic raw);

  @protected
  List<BridgeHistoryEntry> dco_decode_list_bridge_history_entry(dynamic raw);

  @protected
  List<BridgeLlmPreset> dco_decode_list_bridge_llm_preset(dynamic raw);

  @protected
  List<BridgeLlmVendorKey> dco_decode_list_bridge_llm_vendor_key(dynamic raw);

  @protected
  List<BridgePlaceholderFill> dco_decode_list_bridge_placeholder_fill(
    dynamic raw,
  );

  @protected
  List<BridgePrefillRow> dco_decode_list_bridge_prefill_row(dynamic raw);

  @protected
  List<BridgeScenario> dco_decode_list_bridge_scenario(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeEvalEvent> sse_decode_StreamSink_bridge_eval_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeEventEnvelope>
  sse_decode_StreamSink_bridge_event_envelope_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeAsrEdit sse_decode_box_autoadd_bridge_asr_edit(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCommand sse_decode_box_autoadd_bridge_command(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalSummary sse_decode_box_autoadd_bridge_eval_summary(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryFilter sse_decode_box_autoadd_bridge_history_filter(
    SseDeserializer deserializer,
  );

  @protected
  BridgeLlmEdit sse_decode_box_autoadd_bridge_llm_edit(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRectifyBehavior sse_decode_box_autoadd_bridge_rectify_behavior(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionStyle sse_decode_box_autoadd_bridge_session_style(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  BridgeAbout sse_decode_bridge_about(SseDeserializer deserializer);

  @protected
  BridgeAdvancedConfig sse_decode_bridge_advanced_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAsrAliyun sse_decode_bridge_asr_aliyun(SseDeserializer deserializer);

  @protected
  BridgeAsrAliyunEdit sse_decode_bridge_asr_aliyun_edit(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAsrAzure sse_decode_bridge_asr_azure(SseDeserializer deserializer);

  @protected
  BridgeAsrAzureEdit sse_decode_bridge_asr_azure_edit(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAsrConnection sse_decode_bridge_asr_connection(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAsrEdit sse_decode_bridge_asr_edit(SseDeserializer deserializer);

  @protected
  BridgeAsrTencent sse_decode_bridge_asr_tencent(SseDeserializer deserializer);

  @protected
  BridgeAsrTencentEdit sse_decode_bridge_asr_tencent_edit(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAsrVolcengine sse_decode_bridge_asr_volcengine(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAsrVolcengineEdit sse_decode_bridge_asr_volcengine_edit(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCommand sse_decode_bridge_command(SseDeserializer deserializer);

  @protected
  BridgeConnection sse_decode_bridge_connection(SseDeserializer deserializer);

  @protected
  BridgeEngineTiming sse_decode_bridge_engine_timing(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalCaseDetail sse_decode_bridge_eval_case_detail(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalCategory sse_decode_bridge_eval_category(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalEvent sse_decode_bridge_eval_event(SseDeserializer deserializer);

  @protected
  BridgeEvalSummary sse_decode_bridge_eval_summary(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer);

  @protected
  BridgeEventEnvelope sse_decode_bridge_event_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryConfig sse_decode_bridge_history_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryEntry sse_decode_bridge_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryFilter sse_decode_bridge_history_filter(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInsertionTiming sse_decode_bridge_insertion_timing(
    SseDeserializer deserializer,
  );

  @protected
  BridgeKeyEdit sse_decode_bridge_key_edit(SseDeserializer deserializer);

  @protected
  BridgeKeyStatus sse_decode_bridge_key_status(SseDeserializer deserializer);

  @protected
  BridgeLlmConnection sse_decode_bridge_llm_connection(
    SseDeserializer deserializer,
  );

  @protected
  BridgeLlmEdit sse_decode_bridge_llm_edit(SseDeserializer deserializer);

  @protected
  BridgeLlmPreset sse_decode_bridge_llm_preset(SseDeserializer deserializer);

  @protected
  BridgeLlmVendorKey sse_decode_bridge_llm_vendor_key(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlaceholderFill sse_decode_bridge_placeholder_fill(
    SseDeserializer deserializer,
  );

  @protected
  BridgePrefillRow sse_decode_bridge_prefill_row(SseDeserializer deserializer);

  @protected
  BridgeRectifyBehavior sse_decode_bridge_rectify_behavior(
    SseDeserializer deserializer,
  );

  @protected
  BridgeScenario sse_decode_bridge_scenario(SseDeserializer deserializer);

  @protected
  BridgeSessionState sse_decode_bridge_session_state(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionStyle sse_decode_bridge_session_style(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeEvalCaseDetail> sse_decode_list_bridge_eval_case_detail(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeEvalCategory> sse_decode_list_bridge_eval_category(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeHistoryEntry> sse_decode_list_bridge_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeLlmPreset> sse_decode_list_bridge_llm_preset(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeLlmVendorKey> sse_decode_list_bridge_llm_vendor_key(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgePlaceholderFill> sse_decode_list_bridge_placeholder_fill(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgePrefillRow> sse_decode_list_bridge_prefill_row(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeScenario> sse_decode_list_bridge_scenario(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_eval_event_Sse(
    RustStreamSink<BridgeEvalEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_event_envelope_Sse(
    RustStreamSink<BridgeEventEnvelope> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_asr_edit(
    BridgeAsrEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_command(
    BridgeCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_eval_summary(
    BridgeEvalSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_history_filter(
    BridgeHistoryFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_llm_edit(
    BridgeLlmEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_rectify_behavior(
    BridgeRectifyBehavior self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_style(
    BridgeSessionStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_about(BridgeAbout self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_advanced_config(
    BridgeAdvancedConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_aliyun(
    BridgeAsrAliyun self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_aliyun_edit(
    BridgeAsrAliyunEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_azure(
    BridgeAsrAzure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_azure_edit(
    BridgeAsrAzureEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_connection(
    BridgeAsrConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_edit(BridgeAsrEdit self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_asr_tencent(
    BridgeAsrTencent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_tencent_edit(
    BridgeAsrTencentEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_volcengine(
    BridgeAsrVolcengine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asr_volcengine_edit(
    BridgeAsrVolcengineEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_command(BridgeCommand self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_connection(
    BridgeConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_engine_timing(
    BridgeEngineTiming self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_case_detail(
    BridgeEvalCaseDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_category(
    BridgeEvalCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_event(
    BridgeEvalEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_summary(
    BridgeEvalSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_event_envelope(
    BridgeEventEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_history_config(
    BridgeHistoryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_history_entry(
    BridgeHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_history_filter(
    BridgeHistoryFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_insertion_timing(
    BridgeInsertionTiming self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_key_edit(BridgeKeyEdit self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_key_status(
    BridgeKeyStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_llm_connection(
    BridgeLlmConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_llm_edit(BridgeLlmEdit self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_llm_preset(
    BridgeLlmPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_llm_vendor_key(
    BridgeLlmVendorKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_placeholder_fill(
    BridgePlaceholderFill self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_prefill_row(
    BridgePrefillRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rectify_behavior(
    BridgeRectifyBehavior self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_scenario(
    BridgeScenario self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_state(
    BridgeSessionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_style(
    BridgeSessionStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_eval_case_detail(
    List<BridgeEvalCaseDetail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_eval_category(
    List<BridgeEvalCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_history_entry(
    List<BridgeHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_llm_preset(
    List<BridgeLlmPreset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_llm_vendor_key(
    List<BridgeLlmVendorKey> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_placeholder_fill(
    List<BridgePlaceholderFill> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_prefill_row(
    List<BridgePrefillRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_scenario(
    List<BridgeScenario> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
