// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<BridgeEvalEvent> dco_decode_StreamSink_bridge_eval_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeEventEnvelope>
  dco_decode_StreamSink_bridge_event_envelope_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeCommand dco_decode_box_autoadd_bridge_command(dynamic raw);

  @protected
  BridgeEvalSummary dco_decode_box_autoadd_bridge_eval_summary(dynamic raw);

  @protected
  BridgeCommand dco_decode_bridge_command(dynamic raw);

  @protected
  BridgeEvalCaseDetail dco_decode_bridge_eval_case_detail(dynamic raw);

  @protected
  BridgeEvalCategory dco_decode_bridge_eval_category(dynamic raw);

  @protected
  BridgeEvalEvent dco_decode_bridge_eval_event(dynamic raw);

  @protected
  BridgeEvalSummary dco_decode_bridge_eval_summary(dynamic raw);

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw);

  @protected
  BridgeEventEnvelope dco_decode_bridge_event_envelope(dynamic raw);

  @protected
  BridgeHistoryConfig dco_decode_bridge_history_config(dynamic raw);

  @protected
  BridgeHistoryEntry dco_decode_bridge_history_entry(dynamic raw);

  @protected
  BridgeScenario dco_decode_bridge_scenario(dynamic raw);

  @protected
  BridgeSessionState dco_decode_bridge_session_state(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeEvalCaseDetail> dco_decode_list_bridge_eval_case_detail(
    dynamic raw,
  );

  @protected
  List<BridgeEvalCategory> dco_decode_list_bridge_eval_category(dynamic raw);

  @protected
  List<BridgeHistoryEntry> dco_decode_list_bridge_history_entry(dynamic raw);

  @protected
  List<BridgeScenario> dco_decode_list_bridge_scenario(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeEvalEvent> sse_decode_StreamSink_bridge_eval_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeEventEnvelope>
  sse_decode_StreamSink_bridge_event_envelope_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeCommand sse_decode_box_autoadd_bridge_command(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalSummary sse_decode_box_autoadd_bridge_eval_summary(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCommand sse_decode_bridge_command(SseDeserializer deserializer);

  @protected
  BridgeEvalCaseDetail sse_decode_bridge_eval_case_detail(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalCategory sse_decode_bridge_eval_category(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvalEvent sse_decode_bridge_eval_event(SseDeserializer deserializer);

  @protected
  BridgeEvalSummary sse_decode_bridge_eval_summary(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer);

  @protected
  BridgeEventEnvelope sse_decode_bridge_event_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryConfig sse_decode_bridge_history_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryEntry sse_decode_bridge_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  BridgeScenario sse_decode_bridge_scenario(SseDeserializer deserializer);

  @protected
  BridgeSessionState sse_decode_bridge_session_state(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeEvalCaseDetail> sse_decode_list_bridge_eval_case_detail(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeEvalCategory> sse_decode_list_bridge_eval_category(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeHistoryEntry> sse_decode_list_bridge_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeScenario> sse_decode_list_bridge_scenario(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_eval_event_Sse(
    RustStreamSink<BridgeEvalEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_event_envelope_Sse(
    RustStreamSink<BridgeEventEnvelope> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_command(
    BridgeCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_eval_summary(
    BridgeEvalSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_command(BridgeCommand self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_eval_case_detail(
    BridgeEvalCaseDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_category(
    BridgeEvalCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_event(
    BridgeEvalEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_eval_summary(
    BridgeEvalSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_event_envelope(
    BridgeEventEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_history_config(
    BridgeHistoryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_history_entry(
    BridgeHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_scenario(
    BridgeScenario self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_state(
    BridgeSessionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_eval_case_detail(
    List<BridgeEvalCaseDetail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_eval_category(
    List<BridgeEvalCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_history_entry(
    List<BridgeHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_scenario(
    List<BridgeScenario> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
