// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1001246574;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_spokenrectifier_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCreateEngine({required List<String> llmResponses});

  Future<void> crateApiCreateFakeEngine({required List<String> llmResponses});

  Future<void> crateApiExecute({required BridgeCommand command});

  Future<void> crateApiFakeBeginSession();

  Future<void> crateApiFakeSay({required String text});

  Future<void> crateApiFakeSilence({required BigInt elapsedMs});

  Future<void> crateApiHistoryClear();

  Future<List<BridgeHistoryEntry>> crateApiHistoryList();

  Future<List<String>> crateApiInsertedTexts();

  Future<String> crateApiOpenConfigFile();

  Future<BridgeSessionState> crateApiState();

  Future<BridgeStyle> crateApiStyle();

  Stream<BridgeEventEnvelope> crateApiSubscribe();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCreateEngine({required List<String> llmResponses}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(llmResponses, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateEngineConstMeta,
        argValues: [llmResponses],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateEngineConstMeta => const TaskConstMeta(
    debugName: "create_engine",
    argNames: ["llmResponses"],
  );

  @override
  Future<void> crateApiCreateFakeEngine({required List<String> llmResponses}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(llmResponses, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateFakeEngineConstMeta,
        argValues: [llmResponses],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateFakeEngineConstMeta => const TaskConstMeta(
    debugName: "create_fake_engine",
    argNames: ["llmResponses"],
  );

  @override
  Future<void> crateApiExecute({required BridgeCommand command}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_command(command, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExecuteConstMeta,
        argValues: [command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteConstMeta =>
      const TaskConstMeta(debugName: "execute", argNames: ["command"]);

  @override
  Future<void> crateApiFakeBeginSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFakeBeginSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFakeBeginSessionConstMeta =>
      const TaskConstMeta(debugName: "fake_begin_session", argNames: []);

  @override
  Future<void> crateApiFakeSay({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFakeSayConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFakeSayConstMeta =>
      const TaskConstMeta(debugName: "fake_say", argNames: ["text"]);

  @override
  Future<void> crateApiFakeSilence({required BigInt elapsedMs}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(elapsedMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFakeSilenceConstMeta,
        argValues: [elapsedMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFakeSilenceConstMeta =>
      const TaskConstMeta(debugName: "fake_silence", argNames: ["elapsedMs"]);

  @override
  Future<void> crateApiHistoryClear() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHistoryClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryClearConstMeta =>
      const TaskConstMeta(debugName: "history_clear", argNames: []);

  @override
  Future<List<BridgeHistoryEntry>> crateApiHistoryList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bridge_history_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHistoryListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryListConstMeta =>
      const TaskConstMeta(debugName: "history_list", argNames: []);

  @override
  Future<List<String>> crateApiInsertedTexts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInsertedTextsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInsertedTextsConstMeta =>
      const TaskConstMeta(debugName: "inserted_texts", argNames: []);

  @override
  Future<String> crateApiOpenConfigFile() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiOpenConfigFileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenConfigFileConstMeta =>
      const TaskConstMeta(debugName: "open_config_file", argNames: []);

  @override
  Future<BridgeSessionState> crateApiState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_session_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateConstMeta =>
      const TaskConstMeta(debugName: "state", argNames: []);

  @override
  Future<BridgeStyle> crateApiStyle() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_style,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStyleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStyleConstMeta =>
      const TaskConstMeta(debugName: "style", argNames: []);

  @override
  Stream<BridgeEventEnvelope> crateApiSubscribe() {
    final sink = RustStreamSink<BridgeEventEnvelope>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_bridge_event_envelope_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 13,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSubscribeConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSubscribeConstMeta =>
      const TaskConstMeta(debugName: "subscribe", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<BridgeEventEnvelope>
  dco_decode_StreamSink_bridge_event_envelope_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeCommand dco_decode_box_autoadd_bridge_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_command(raw);
  }

  @protected
  BridgeCommand dco_decode_bridge_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return BridgeCommand_StartSession();
      case 1:
        return BridgeCommand_StopSession();
      case 2:
        return BridgeCommand_Cancel();
      case 3:
        return BridgeCommand_ConfirmInsert();
      case 4:
        return BridgeCommand_Reroll();
      case 5:
        return BridgeCommand_UpdatePreviewText(text: dco_decode_String(raw[1]));
      case 6:
        return BridgeCommand_SetStyle(style: dco_decode_bridge_style(raw[1]));
      case 7:
        return BridgeCommand_RectifyText(
          rawTranscript: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return BridgeEvent_SessionStateChanged(
          from: dco_decode_bridge_session_state(raw[1]),
          to: dco_decode_bridge_session_state(raw[2]),
        );
      case 1:
        return BridgeEvent_LiveTranscriptUpdated(
          text: dco_decode_String(raw[1]),
        );
      case 2:
        return BridgeEvent_ParagraphMarked();
      case 3:
        return BridgeEvent_SpeechActivityChanged(
          speaking: dco_decode_bool(raw[1]),
        );
      case 4:
        return BridgeEvent_RectifiedTextChunk(delta: dco_decode_String(raw[1]));
      case 5:
        return BridgeEvent_PreviewTextUpdated(text: dco_decode_String(raw[1]));
      case 6:
        return BridgeEvent_TextInserted(text: dco_decode_String(raw[1]));
      case 7:
        return BridgeEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BridgeEventEnvelope dco_decode_bridge_event_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeEventEnvelope(
      seq: dco_decode_u_64(arr[0]),
      sessionId: dco_decode_u_64(arr[1]),
      atMs: dco_decode_u_64(arr[2]),
      event: dco_decode_bridge_event(arr[3]),
    );
  }

  @protected
  BridgeHistoryEntry dco_decode_bridge_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeHistoryEntry(
      id: dco_decode_i_64(arr[0]),
      createdAtMs: dco_decode_u_64(arr[1]),
      rawTranscript: dco_decode_String(arr[2]),
      rectifiedText: dco_decode_String(arr[3]),
    );
  }

  @protected
  BridgeSessionState dco_decode_bridge_session_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeSessionState.values[raw as int];
  }

  @protected
  BridgeStyle dco_decode_bridge_style(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeStyle.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BridgeHistoryEntry> dco_decode_list_bridge_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_history_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<BridgeEventEnvelope>
  sse_decode_StreamSink_bridge_event_envelope_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeCommand sse_decode_box_autoadd_bridge_command(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_command(deserializer));
  }

  @protected
  BridgeCommand sse_decode_bridge_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return BridgeCommand_StartSession();
      case 1:
        return BridgeCommand_StopSession();
      case 2:
        return BridgeCommand_Cancel();
      case 3:
        return BridgeCommand_ConfirmInsert();
      case 4:
        return BridgeCommand_Reroll();
      case 5:
        var var_text = sse_decode_String(deserializer);
        return BridgeCommand_UpdatePreviewText(text: var_text);
      case 6:
        var var_style = sse_decode_bridge_style(deserializer);
        return BridgeCommand_SetStyle(style: var_style);
      case 7:
        var var_rawTranscript = sse_decode_String(deserializer);
        return BridgeCommand_RectifyText(rawTranscript: var_rawTranscript);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_from = sse_decode_bridge_session_state(deserializer);
        var var_to = sse_decode_bridge_session_state(deserializer);
        return BridgeEvent_SessionStateChanged(from: var_from, to: var_to);
      case 1:
        var var_text = sse_decode_String(deserializer);
        return BridgeEvent_LiveTranscriptUpdated(text: var_text);
      case 2:
        return BridgeEvent_ParagraphMarked();
      case 3:
        var var_speaking = sse_decode_bool(deserializer);
        return BridgeEvent_SpeechActivityChanged(speaking: var_speaking);
      case 4:
        var var_delta = sse_decode_String(deserializer);
        return BridgeEvent_RectifiedTextChunk(delta: var_delta);
      case 5:
        var var_text = sse_decode_String(deserializer);
        return BridgeEvent_PreviewTextUpdated(text: var_text);
      case 6:
        var var_text = sse_decode_String(deserializer);
        return BridgeEvent_TextInserted(text: var_text);
      case 7:
        var var_message = sse_decode_String(deserializer);
        return BridgeEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BridgeEventEnvelope sse_decode_bridge_event_envelope(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seq = sse_decode_u_64(deserializer);
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_atMs = sse_decode_u_64(deserializer);
    var var_event = sse_decode_bridge_event(deserializer);
    return BridgeEventEnvelope(
      seq: var_seq,
      sessionId: var_sessionId,
      atMs: var_atMs,
      event: var_event,
    );
  }

  @protected
  BridgeHistoryEntry sse_decode_bridge_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_createdAtMs = sse_decode_u_64(deserializer);
    var var_rawTranscript = sse_decode_String(deserializer);
    var var_rectifiedText = sse_decode_String(deserializer);
    return BridgeHistoryEntry(
      id: var_id,
      createdAtMs: var_createdAtMs,
      rawTranscript: var_rawTranscript,
      rectifiedText: var_rectifiedText,
    );
  }

  @protected
  BridgeSessionState sse_decode_bridge_session_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeSessionState.values[inner];
  }

  @protected
  BridgeStyle sse_decode_bridge_style(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeStyle.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeHistoryEntry> sse_decode_list_bridge_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_bridge_event_envelope_Sse(
    RustStreamSink<BridgeEventEnvelope> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_event_envelope,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_command(
    BridgeCommand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_command(self, serializer);
  }

  @protected
  void sse_encode_bridge_command(BridgeCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case BridgeCommand_StartSession():
        sse_encode_i_32(0, serializer);
      case BridgeCommand_StopSession():
        sse_encode_i_32(1, serializer);
      case BridgeCommand_Cancel():
        sse_encode_i_32(2, serializer);
      case BridgeCommand_ConfirmInsert():
        sse_encode_i_32(3, serializer);
      case BridgeCommand_Reroll():
        sse_encode_i_32(4, serializer);
      case BridgeCommand_UpdatePreviewText(text: final text):
        sse_encode_i_32(5, serializer);
        sse_encode_String(text, serializer);
      case BridgeCommand_SetStyle(style: final style):
        sse_encode_i_32(6, serializer);
        sse_encode_bridge_style(style, serializer);
      case BridgeCommand_RectifyText(rawTranscript: final rawTranscript):
        sse_encode_i_32(7, serializer);
        sse_encode_String(rawTranscript, serializer);
    }
  }

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case BridgeEvent_SessionStateChanged(from: final from, to: final to):
        sse_encode_i_32(0, serializer);
        sse_encode_bridge_session_state(from, serializer);
        sse_encode_bridge_session_state(to, serializer);
      case BridgeEvent_LiveTranscriptUpdated(text: final text):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
      case BridgeEvent_ParagraphMarked():
        sse_encode_i_32(2, serializer);
      case BridgeEvent_SpeechActivityChanged(speaking: final speaking):
        sse_encode_i_32(3, serializer);
        sse_encode_bool(speaking, serializer);
      case BridgeEvent_RectifiedTextChunk(delta: final delta):
        sse_encode_i_32(4, serializer);
        sse_encode_String(delta, serializer);
      case BridgeEvent_PreviewTextUpdated(text: final text):
        sse_encode_i_32(5, serializer);
        sse_encode_String(text, serializer);
      case BridgeEvent_TextInserted(text: final text):
        sse_encode_i_32(6, serializer);
        sse_encode_String(text, serializer);
      case BridgeEvent_Error(message: final message):
        sse_encode_i_32(7, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_bridge_event_envelope(
    BridgeEventEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.seq, serializer);
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_u_64(self.atMs, serializer);
    sse_encode_bridge_event(self.event, serializer);
  }

  @protected
  void sse_encode_bridge_history_entry(
    BridgeHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_u_64(self.createdAtMs, serializer);
    sse_encode_String(self.rawTranscript, serializer);
    sse_encode_String(self.rectifiedText, serializer);
  }

  @protected
  void sse_encode_bridge_session_state(
    BridgeSessionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_style(BridgeStyle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_history_entry(
    List<BridgeHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
