// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `launch_editor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// The about pane's one read (version, license, repository).
Future<BridgeAbout> about() => RustLib.instance.api.crateApiAboutAbout();

/// Open the shared config file in the system text editor — the tray's
/// settings entry. Creates a commented stub first when no config file
/// exists yet (see `settings::ensure_shared_config` for where). Returns
/// the path that was opened.
Future<String> openConfigFile() =>
    RustLib.instance.api.crateApiAboutOpenConfigFile();

/// What the about pane paints. The version is the app crate's manifest
/// (kept in step with the Flutter `pubspec.yaml` — bump both together).
class BridgeAbout {
  final String version;
  final String license;

  /// The public repository; absent until the open-source packaging
  /// (ticket 11) names one.
  final String? repoUrl;

  const BridgeAbout({
    required this.version,
    required this.license,
    this.repoUrl,
  });

  @override
  int get hashCode => version.hashCode ^ license.hashCode ^ repoUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAbout &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          license == other.license &&
          repoUrl == other.repoUrl;
}
