// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// The advanced domain's one read: the session and insertion latency
/// parameters, effective right now (the editable form's initial paint).
Future<BridgeAdvancedConfig> advancedConfig() =>
    RustLib.instance.api.crateApiAdvancedAdvancedConfig();

/// Write the form's `[engine]` model (passage mode + the three timings)
/// into the layer files and hand it to the live engine at once
/// (ADR-0007, revised): both runtime commands adopt the saved values
/// immediately, and each session snapshots what it opens with — so the
/// save applies from the NEXT session on, while the file stays the
/// truth across launches. The quick panel's passage toggle stays the
/// runtime-only quick switch; this one persists. Returns the re-read
/// view.
Future<BridgeEngineTiming> setEngineSettings({
  required bool passageMode,
  required BigInt paragraphSilenceMs,
  required BigInt sessionEndSilenceMs,
  required BigInt rectifyTimeoutMs,
}) => RustLib.instance.api.crateApiAdvancedSetEngineSettings(
  passageMode: passageMode,
  paragraphSilenceMs: paragraphSilenceMs,
  sessionEndSilenceMs: sessionEndSilenceMs,
  rectifyTimeoutMs: rectifyTimeoutMs,
);

/// Write the form's `[insertion]` model into the layer files and apply
/// it to the live inserter at once (ADR-0007, 2026-08-28 revision):
/// insertion is discrete per-confirm, so the swap is true real-time —
/// the very next ConfirmInsert runs with the new mode and pacing. A
/// no-op apply on the fake engine (tests and demos hold no target
/// window); the file write still lands. Returns the re-read view.
Future<BridgeInsertionTiming> setInsertionTiming({
  required String mode,
  required BigInt focusSettleMs,
  required BigInt pasteSettleMs,
  required BigInt typingDelayMs,
}) => RustLib.instance.api.crateApiAdvancedSetInsertionTiming(
  mode: mode,
  focusSettleMs: focusSettleMs,
  pasteSettleMs: pasteSettleMs,
  typingDelayMs: typingDelayMs,
);

/// Both timing cards in one read.
class BridgeAdvancedConfig {
  final BridgeEngineTiming engine;
  final BridgeInsertionTiming insertion;

  const BridgeAdvancedConfig({required this.engine, required this.insertion});

  @override
  int get hashCode => engine.hashCode ^ insertion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAdvancedConfig &&
          runtimeType == other.runtimeType &&
          engine == other.engine &&
          insertion == other.insertion;
}

/// The effective `[engine]` timings as the advanced pane paints them
/// (read-only; see ADR-0007 for why they stay file-only).
class BridgeEngineTiming {
  final bool passageMode;
  final BigInt paragraphSilenceMs;
  final BigInt sessionEndSilenceMs;
  final BigInt rectifyTimeoutMs;

  const BridgeEngineTiming({
    required this.passageMode,
    required this.paragraphSilenceMs,
    required this.sessionEndSilenceMs,
    required this.rectifyTimeoutMs,
  });

  @override
  int get hashCode =>
      passageMode.hashCode ^
      paragraphSilenceMs.hashCode ^
      sessionEndSilenceMs.hashCode ^
      rectifyTimeoutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEngineTiming &&
          runtimeType == other.runtimeType &&
          passageMode == other.passageMode &&
          paragraphSilenceMs == other.paragraphSilenceMs &&
          sessionEndSilenceMs == other.sessionEndSilenceMs &&
          rectifyTimeoutMs == other.rectifyTimeoutMs;
}

/// The effective `[insertion]` timings as the advanced pane paints them.
class BridgeInsertionTiming {
  /// `paste` or `typing`.
  final String mode;
  final BigInt focusSettleMs;
  final BigInt pasteSettleMs;
  final BigInt typingDelayMs;

  const BridgeInsertionTiming({
    required this.mode,
    required this.focusSettleMs,
    required this.pasteSettleMs,
    required this.typingDelayMs,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      focusSettleMs.hashCode ^
      pasteSettleMs.hashCode ^
      typingDelayMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInsertionTiming &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          focusSettleMs == other.focusSettleMs &&
          pasteSettleMs == other.pasteSettleMs &&
          typingDelayMs == other.typingDelayMs;
}
