// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_value`

/// Whether the Run key currently carries our value — the switch's
/// truth. Presence is the whole test: whatever data it holds was a
/// write someone meant. An unopenable key reads off (the switch can be
/// re-armed, not trusted).
Future<bool> autostartEnabled() =>
    RustLib.instance.api.crateApiAutostartAutostartEnabled();

/// Turn autostart on (write the quoted exe) or off (delete the value).
/// Off is idempotent — a value already gone is the off we asked for.
/// Returns the re-read state, the switch's next paint.
Future<bool> setAutostart({required bool enabled}) =>
    RustLib.instance.api.crateApiAutostartSetAutostart(enabled: enabled);
