// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'connection.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `asr_view`, `bridge_key`, `llm_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// The preset port (ADR-0019 item 5): the settings pane's chip row, read
/// from the engine-side single source rather than copied into Dart. The
/// blank 自定义 seventh chip is the pane's own — it names no preset.
Future<List<BridgeLlmPreset>> llmPresets() =>
    RustLib.instance.api.crateApiConnectionLlmPresets();

/// The effective `[asr]` and `[llm]` connections from the layer files —
/// the connection domain's initial paint. File-level and
/// engine-independent: the engine adopts the config at its creation,
/// and a save re-adopts it at once via [`apply_connection_configs`] —
/// next session (ASR) / next attempt (LLM), no restart (ADR-0010). The
/// fidelity-eval run builds its own engine per run, unaffected.
Future<BridgeConnection> connectionConfig() =>
    RustLib.instance.api.crateApiConnectionConnectionConfig();

/// Write the editor's whole `[asr]` card back into the layer files (see
/// `save_asr_connection` for the placement and preservation rules —
/// common fields plus every vendor sub-section, every secret to the
/// local layer only) and return the re-read view — the file's truth,
/// not the ask.
Future<BridgeAsrConnection> setAsrConnection({required BridgeAsrEdit edit}) =>
    RustLib.instance.api.crateApiConnectionSetAsrConnection(edit: edit);

/// The settings pane's live endpoint preview: the WebSocket URL the
/// form's current fields resolve to, recomputed while the user types
/// or switches the provider chip — the same [`AsrConfig::endpoint`]
/// derivation the loaded view previews with, so there is exactly one.
Future<String?> asrEndpointPreview({
  required String provider,
  required String model,
  String? baseUrl,
  String? workspaceId,
  required String region,
  String? appId,
}) => RustLib.instance.api.crateApiConnectionAsrEndpointPreview(
  provider: provider,
  model: model,
  baseUrl: baseUrl,
  workspaceId: workspaceId,
  region: region,
  appId: appId,
);

/// Write the editor's `[llm]` model back into the layer files (see
/// `save_llm_connection`) and return the re-read view — the file's
/// truth, not the ask. The format and the thinking group ride the edit
/// whole (ADR-0019 items 1/2); the group's boxes are the JSON text the
/// pane holds, and a bad one refuses the save before anything is
/// written.
Future<BridgeLlmConnection> setLlmConnection({required BridgeLlmEdit edit}) =>
    RustLib.instance.api.crateApiConnectionSetLlmConnection(edit: edit);

/// Adopt the saved `[asr]` / `[llm]` connections — and, riding the same
/// rebuilt client, every `[rectify]` key (ADR-0010, scope extended by
/// ADR-0015) — into the live engine at once: the settings window calls
/// this right after a save lands, so the next session opens with the new
/// ASR provider and the next rectify attempt with the new LLM and the new
/// rectify behavior (thinking policy, prefill, the light-touch gate, the
/// extra directive), no restart. Re-reads the layer files and rebuilds
/// both collaborators through the same factory the startup path uses
/// (mic-only fallback included: clearing the provider's credentials
/// really does drop back to mic+VAD at runtime).
///
/// The rebuild happens before any handover, so any refusal (an incomplete
/// credential set, an unadapted provider, the demo-mode LLM that has no
/// runtime script — all tested in `engine_factory`) returns `Err` and
/// keeps BOTH previous collaborators running; the files stay saved either
/// way, so the next launch adopts them regardless. The swap semantics are
/// locked by the engine's `live_swap` tests. A no-op on the fake engine
/// (tests and demos hold no production collaborators to swap).
Future<void> applyConnectionConfigs() =>
    RustLib.instance.api.crateApiConnectionApplyConnectionConfigs();

/// `[asr.aliyun]` for the pane.
class BridgeAsrAliyun {
  final String? workspaceId;
  final String region;

  const BridgeAsrAliyun({this.workspaceId, required this.region});

  @override
  int get hashCode => workspaceId.hashCode ^ region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAliyun &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          region == other.region;
}

class BridgeAsrAliyunEdit {
  final String? workspaceId;
  final String region;

  const BridgeAsrAliyunEdit({this.workspaceId, required this.region});

  @override
  int get hashCode => workspaceId.hashCode ^ region.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAliyunEdit &&
          runtimeType == other.runtimeType &&
          workspaceId == other.workspaceId &&
          region == other.region;
}

/// `[asr.azure]` for the pane (adapter not scheduled).
class BridgeAsrAzure {
  final String? region;
  final String? endpointId;

  const BridgeAsrAzure({this.region, this.endpointId});

  @override
  int get hashCode => region.hashCode ^ endpointId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAzure &&
          runtimeType == other.runtimeType &&
          region == other.region &&
          endpointId == other.endpointId;
}

class BridgeAsrAzureEdit {
  final String? region;
  final String? endpointId;

  const BridgeAsrAzureEdit({this.region, this.endpointId});

  @override
  int get hashCode => region.hashCode ^ endpointId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrAzureEdit &&
          runtimeType == other.runtimeType &&
          region == other.region &&
          endpointId == other.endpointId;
}

/// The effective `[asr]` connection as the settings pane paints it: the
/// common segment's folded fields, every vendor sub-section (the pane
/// renders the active one), the resolved endpoint (a read-only preview;
/// `None` for providers without an adapter yet), and each secret's
/// placement.
class BridgeAsrConnection {
  /// `aliyun` / `volcengine` / `tencent` / `openai` / `azure`.
  final String provider;
  final String model;
  final String language;
  final String? baseUrl;

  /// The WebSocket URL the current fields resolve to.
  final String? endpoint;

  /// The common Bearer key pair (the active provider's, when its
  /// family is the Bearer one).
  final BridgeKeyStatus key;
  final BridgeAsrAliyun aliyun;
  final BridgeAsrVolcengine volcengine;
  final BridgeAsrTencent tencent;
  final BridgeAsrAzure azure;

  const BridgeAsrConnection({
    required this.provider,
    required this.model,
    required this.language,
    this.baseUrl,
    this.endpoint,
    required this.key,
    required this.aliyun,
    required this.volcengine,
    required this.tencent,
    required this.azure,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      model.hashCode ^
      language.hashCode ^
      baseUrl.hashCode ^
      endpoint.hashCode ^
      key.hashCode ^
      aliyun.hashCode ^
      volcengine.hashCode ^
      tencent.hashCode ^
      azure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrConnection &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          model == other.model &&
          language == other.language &&
          baseUrl == other.baseUrl &&
          endpoint == other.endpoint &&
          key == other.key &&
          aliyun == other.aliyun &&
          volcengine == other.volcengine &&
          tencent == other.tencent &&
          azure == other.azure;
}

/// The editor's whole `[asr]` card, mirroring the schema's
/// [`AsrConnectionEdit`]: common fields plus every vendor sub-section
/// (a provider switch never clears another vendor's fields).
class BridgeAsrEdit {
  final String provider;
  final String model;
  final String language;
  final String? baseUrl;
  final BridgeKeyEdit apiKey;
  final BridgeAsrAliyunEdit aliyun;
  final BridgeAsrVolcengineEdit volcengine;
  final BridgeAsrTencentEdit tencent;
  final BridgeAsrAzureEdit azure;

  const BridgeAsrEdit({
    required this.provider,
    required this.model,
    required this.language,
    this.baseUrl,
    required this.apiKey,
    required this.aliyun,
    required this.volcengine,
    required this.tencent,
    required this.azure,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      model.hashCode ^
      language.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      aliyun.hashCode ^
      volcengine.hashCode ^
      tencent.hashCode ^
      azure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrEdit &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          model == other.model &&
          language == other.language &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          aliyun == other.aliyun &&
          volcengine == other.volcengine &&
          tencent == other.tencent &&
          azure == other.azure;
}

/// `[asr.tencent]` for the pane; both account credentials echo per
/// the diff-echo key block.
class BridgeAsrTencent {
  final String? appId;
  final BridgeKeyStatus secretId;
  final BridgeKeyStatus secretKey;

  const BridgeAsrTencent({
    this.appId,
    required this.secretId,
    required this.secretKey,
  });

  @override
  int get hashCode => appId.hashCode ^ secretId.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrTencent &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          secretId == other.secretId &&
          secretKey == other.secretKey;
}

class BridgeAsrTencentEdit {
  final String? appId;
  final BridgeKeyEdit secretId;
  final BridgeKeyEdit secretKey;

  const BridgeAsrTencentEdit({
    this.appId,
    required this.secretId,
    required this.secretKey,
  });

  @override
  int get hashCode => appId.hashCode ^ secretId.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrTencentEdit &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          secretId == other.secretId &&
          secretKey == other.secretKey;
}

/// `[asr.volcengine]` for the pane; the access token echoes per the
/// diff-echo key block.
class BridgeAsrVolcengine {
  final String? appId;
  final String resourceId;
  final BridgeKeyStatus accessKey;

  const BridgeAsrVolcengine({
    this.appId,
    required this.resourceId,
    required this.accessKey,
  });

  @override
  int get hashCode => appId.hashCode ^ resourceId.hashCode ^ accessKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrVolcengine &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          resourceId == other.resourceId &&
          accessKey == other.accessKey;
}

class BridgeAsrVolcengineEdit {
  final String? appId;
  final String resourceId;
  final BridgeKeyEdit accessKey;

  const BridgeAsrVolcengineEdit({
    this.appId,
    required this.resourceId,
    required this.accessKey,
  });

  @override
  int get hashCode => appId.hashCode ^ resourceId.hashCode ^ accessKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAsrVolcengineEdit &&
          runtimeType == other.runtimeType &&
          appId == other.appId &&
          resourceId == other.resourceId &&
          accessKey == other.accessKey;
}

/// Both connections in one read.
class BridgeConnection {
  final BridgeAsrConnection asr;
  final BridgeLlmConnection llm;

  const BridgeConnection({required this.asr, required this.llm});

  @override
  int get hashCode => asr.hashCode ^ llm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConnection &&
          runtimeType == other.runtimeType &&
          asr == other.asr &&
          llm == other.llm;
}

@freezed
sealed class BridgeKeyEdit with _$BridgeKeyEdit {
  const BridgeKeyEdit._();

  const factory BridgeKeyEdit.keep() = BridgeKeyEdit_Keep;
  const factory BridgeKeyEdit.clear() = BridgeKeyEdit_Clear;
  const factory BridgeKeyEdit.set_(String field0) = BridgeKeyEdit_Set;
}

@freezed
sealed class BridgeKeyStatus with _$BridgeKeyStatus {
  const BridgeKeyStatus._();

  const factory BridgeKeyStatus.unset() = BridgeKeyStatus_Unset;

  /// The stored key (from the local layer only — the loader's
  /// shared-file guard makes that the sole source).
  const factory BridgeKeyStatus.inLocalFile(String field0) =
      BridgeKeyStatus_InLocalFile;
  const factory BridgeKeyStatus.fromEnv(String field0) =
      BridgeKeyStatus_FromEnv;
}

/// The effective `[llm]` connection as the settings pane paints it.
/// `key` is the ACTIVE vendor's resolved pair; `keys` carries every
/// vendor's — a key authenticates exactly one vendor, so the pane
/// re-binds its key block per vendor chip and a switch never shows
/// another vendor's key (ADR-0011).
///
/// The open shape (ADR-0019) rides here resolved: the format axis, the
/// thinking switch's four-state reading, and the three overlays as the
/// JSON text the pane's boxes hold (pretty, so a reopen reformats
/// whatever the file's table ordering was).
class BridgeLlmConnection {
  final String vendor;
  final String baseUrl;
  final String model;

  /// `openai_chat` | `anthropic` | `gemini` (ADR-0019 item 1).
  final String format;
  final BridgeKeyStatus key;
  final List<BridgeLlmVendorKey> keys;

  /// The thinking group's reading: `on` | `off` | `unconfigured` |
  /// `broken`. Only `on` is the switch's painted state — the other
  /// three are one semantic for every consumer (ADR-0019 item 3).
  final String thinkingState;

  /// `broken`'s file-and-key detail, for the card's warning slot.
  final String? thinkingDetail;

  /// The resident overlay's JSON text; `None` when unset.
  final String? bodyJson;
  final String? thinkingOnJson;
  final String? thinkingOffJson;

  const BridgeLlmConnection({
    required this.vendor,
    required this.baseUrl,
    required this.model,
    required this.format,
    required this.key,
    required this.keys,
    required this.thinkingState,
    this.thinkingDetail,
    this.bodyJson,
    this.thinkingOnJson,
    this.thinkingOffJson,
  });

  @override
  int get hashCode =>
      vendor.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      format.hashCode ^
      key.hashCode ^
      keys.hashCode ^
      thinkingState.hashCode ^
      thinkingDetail.hashCode ^
      bodyJson.hashCode ^
      thinkingOnJson.hashCode ^
      thinkingOffJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLlmConnection &&
          runtimeType == other.runtimeType &&
          vendor == other.vendor &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          format == other.format &&
          key == other.key &&
          keys == other.keys &&
          thinkingState == other.thinkingState &&
          thinkingDetail == other.thinkingDetail &&
          bodyJson == other.bodyJson &&
          thinkingOnJson == other.thinkingOnJson &&
          thinkingOffJson == other.thinkingOffJson;
}

/// The editor's whole `[llm]` card: the endpoint fields, the format
/// axis, the thinking switch, and the three overlay boxes as the JSON
/// text they hold (blank or `{}` = that share unset). The save writes
/// exactly this model, so the next load returns what the user saw.
class BridgeLlmEdit {
  final String vendor;
  final String baseUrl;
  final String model;

  /// One of the three format wire names (validated on the Rust side).
  final String format;
  final bool thinkingFields;

  /// The resident overlay's JSON text; blank/`{}`/None = unset.
  final String? bodyJson;
  final String? thinkingOnJson;
  final String? thinkingOffJson;
  final BridgeKeyEdit apiKey;

  const BridgeLlmEdit({
    required this.vendor,
    required this.baseUrl,
    required this.model,
    required this.format,
    required this.thinkingFields,
    this.bodyJson,
    this.thinkingOnJson,
    this.thinkingOffJson,
    required this.apiKey,
  });

  @override
  int get hashCode =>
      vendor.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      format.hashCode ^
      thinkingFields.hashCode ^
      bodyJson.hashCode ^
      thinkingOnJson.hashCode ^
      thinkingOffJson.hashCode ^
      apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLlmEdit &&
          runtimeType == other.runtimeType &&
          vendor == other.vendor &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          format == other.format &&
          thinkingFields == other.thinkingFields &&
          bodyJson == other.bodyJson &&
          thinkingOnJson == other.thinkingOnJson &&
          thinkingOffJson == other.thinkingOffJson &&
          apiKey == other.apiKey;
}

/// One chip's fill, straight from the engine-side single source
/// (`crates/llm::presets`) — the pane never copies the table (ADR-0019
/// item 5). The model rule (only when empty or still a preset name) and
/// the blank custom seventh chip live in the pane, not here.
class BridgeLlmPreset {
  /// The chip's wire name — also the vendor slot it names.
  final String name;
  final String format;
  final String baseUrl;
  final String model;

  /// The 「设置思考字段」 switch the chip stamps.
  final bool thinkingFields;

  /// The two shares as JSON text, for the boxes.
  final String thinkingOnJson;
  final String thinkingOffJson;

  const BridgeLlmPreset({
    required this.name,
    required this.format,
    required this.baseUrl,
    required this.model,
    required this.thinkingFields,
    required this.thinkingOnJson,
    required this.thinkingOffJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      format.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      thinkingFields.hashCode ^
      thinkingOnJson.hashCode ^
      thinkingOffJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLlmPreset &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          format == other.format &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          thinkingFields == other.thinkingFields &&
          thinkingOnJson == other.thinkingOnJson &&
          thinkingOffJson == other.thinkingOffJson;
}

/// One vendor's resolved key pair, for the pane's per-vendor key block.
class BridgeLlmVendorKey {
  final String vendor;
  final BridgeKeyStatus key;

  const BridgeLlmVendorKey({required this.vendor, required this.key});

  @override
  int get hashCode => vendor.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLlmVendorKey &&
          runtimeType == other.runtimeType &&
          vendor == other.vendor &&
          key == other.key;
}
