// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `open_fake_feed`

/// Everything the fake inserter received, in order (demo introspection).
/// The production inserter does not record; insertion outcomes arrive on
/// the event stream instead (`TextInserted` / `Error`).
Future<List<String>> insertedTexts() =>
    RustLib.instance.api.crateApiDemoInsertedTexts();

/// Open the next fake ASR session and allow `fake_say` / `fake_silence` to
/// feed it. Call before `execute(BridgeCommand::StartSession)`.
Future<void> fakeBeginSession() =>
    RustLib.instance.api.crateApiDemoFakeBeginSession();

/// Feed one scripted phrase (partial, then final) into the open session.
Future<void> fakeSay({required String text}) =>
    RustLib.instance.api.crateApiDemoFakeSay(text: text);

/// Feed one scripted cumulative-silence event (milliseconds) into the open
/// session.
Future<void> fakeSilence({required BigInt elapsedMs}) =>
    RustLib.instance.api.crateApiDemoFakeSilence(elapsedMs: elapsedMs);
