// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `token_scripts`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Build the engine behind the bridge with the real default microphone
/// and, when the `[asr]` config carries credentials, the configured
/// provider's cloud adapter streaming real transcripts (see
/// `engine_factory::asr_provider` for the dispatch and its error
/// rules). Without credentials the mic+VAD provider keeps the session
/// semantics (speech activity, silence, device failure). The rectify
/// LLM is the real OpenAI-compatible client when
/// `[llm]` yields a key; the scripted demo LLM otherwise — but that
/// combination is refused under a real ASR key (see `engine_factory`).
/// Insertion is the production inserter (clipboard paste with restore, or
/// typing per the `[insertion]` config). Session semantics load from the
/// `[engine]` section of the layered config files. Idempotent: a second
/// call is a no-op.
Future<void> createEngine({required List<String> llmResponses}) =>
    RustLib.instance.api.crateApiEngineCreateEngine(llmResponses: llmResponses);

/// Build the engine behind the bridge with all-fake collaborators.
/// `llm_responses` become the scripted rectify responses (streamed in small
/// chunks), repeating forever — the demo host never runs dry no matter how
/// many sessions or rerolls come. Idempotent: a second call is a no-op.
Future<void> createFakeEngine({required List<String> llmResponses}) => RustLib
    .instance
    .api
    .crateApiEngineCreateFakeEngine(llmResponses: llmResponses);

/// Submit a command to the engine. Returns an error only for rejected
/// commands (wrong state); asynchronous outcomes arrive on the event stream.
Future<void> execute({required BridgeCommand command}) =>
    RustLib.instance.api.crateApiEngineExecute(command: command);

/// Arm the primary-hotkey hold watcher (ADR-0020). `vks` are Win32
/// virtual-key codes of the current main-flow chord. Returns whether a
/// watch is now live — Dart swallows `WM_HOTKEY` repeats off that.
///
/// Arms for every primary-hotkey session, master switch on or off: the
/// watch owns the chord's release either way, so the auto-repeats of one
/// physical hold can never toggle the session (a switch-off hold used to
/// flicker start/stop through today's tap path). Whether the 400 ms mark
/// upgrades is the engine's call — with the switch off it refuses
/// `MarkQuick`, `is_quick()` stays false, and the hold ends as an
/// ordinary one (a short release keeps recording). A quiet `false`
/// (never an error) when the engine is not recording or `vks` is empty.
/// `stop_on_early_release` is the later press while already recording
/// (today's tap-to-stop); the opening hold that started the session
/// passes false so a short release keeps recording.
///
/// Independent of [`execute`] / `StartSession`: the orb click shares
/// that command and must not start a watch (球左键不跟).
Future<bool> watchHold({
  required List<int> vks,
  required bool stopOnEarlyRelease,
}) => RustLib.instance.api.crateApiEngineWatchHold(
  vks: vks,
  stopOnEarlyRelease: stopOnEarlyRelease,
);

/// Whether the hold watcher is currently running. Dart swallows
/// `WM_HOTKEY` repeats while this is true.
Future<bool> isHolding() => RustLib.instance.api.crateApiEngineIsHolding();

/// Current session state, for initial paint before any event arrives.
Future<BridgeSessionState> state() =>
    RustLib.instance.api.crateApiEngineState();

/// Passage mode as it stands now (config-seeded, runtime-switched) —
/// what the quick panel's toggle paints and what the next session opens
/// with.
Future<bool> passageMode() => RustLib.instance.api.crateApiEnginePassageMode();

/// Hand the keyboard back to the remembered target window — the quick
/// panel's own close path. Self-guarded on the inserter side: a foreign
/// foreground (or no remembered target) is left alone, exactly like the
/// cancel-path restore. No-op on the fake engine.
Future<void> restoreFocus() =>
    RustLib.instance.api.crateApiEngineRestoreFocus();

/// Subscribe the Dart side to the engine's event stream. Each call spawns
/// an independent forwarder; dropping the Dart stream stops it.
Stream<BridgeEventEnvelope> subscribe() =>
    RustLib.instance.api.crateApiEngineSubscribe();

@freezed
sealed class BridgeCommand with _$BridgeCommand {
  const BridgeCommand._();

  const factory BridgeCommand.startSession() = BridgeCommand_StartSession;
  const factory BridgeCommand.stopSession() = BridgeCommand_StopSession;
  const factory BridgeCommand.cancel() = BridgeCommand_Cancel;

  /// The confirm-time slot table rides beside the insert (占位符钉入
  /// 入库): one row per slot whose value the shell's substitution
  /// landed in the inserted text. A pass-through the engine ferries to
  /// the recorder; pin-less and degraded confirms send an empty table.
  const factory BridgeCommand.confirmInsert({
    required List<BridgePlaceholderFill> placeholders,
  }) = BridgeCommand_ConfirmInsert;
  const factory BridgeCommand.reroll() = BridgeCommand_Reroll;
  const factory BridgeCommand.updatePreviewText({required String text}) =
      BridgeCommand_UpdatePreviewText;

  /// The selected scenario's style-directive text and its name (a
  /// pass-through pair the engine carries without interpreting; the
  /// store resolves the name when the session is recorded); `None`
  /// returns to the built-in default register.
  const factory BridgeCommand.setStyleDirective({
    String? directive,
    String? scenario,
  }) = BridgeCommand_SetStyleDirective;

  /// The global directive's text (ticket 22; the engine knows nothing
  /// about where it is stored); `None` unsets it. A live value read at
  /// every request assembly, never pinned per session.
  const factory BridgeCommand.setGlobalDirective({String? directive}) =
      BridgeCommand_SetGlobalDirective;

  /// Passage mode (篇章模式) as it stands now — the value the next
  /// session opens with (the engine snapshots it per session).
  const factory BridgeCommand.setPassageMode({required bool on_}) =
      BridgeCommand_SetPassageMode;

  /// The latency timings as they stand now — the values the next
  /// session opens with (the engine snapshots them per session). The
  /// settings window's advanced form sends this right after the file
  /// write, so the live engine adopts the saved values at once.
  const factory BridgeCommand.setEngineTimings({
    required BigInt paragraphSilenceMs,
    required BigInt sessionEndSilenceMs,
    required BigInt rectifyTimeoutMs,
  }) = BridgeCommand_SetEngineTimings;

  /// Pin a placeholder (钉入) at the current end of the spoken segment
  /// — the Alt+B press while listening. Only valid while recording
  /// (rejected otherwise); the sentinel `‡N‡` appears in the live
  /// transcript at once via the usual `LiveTranscriptUpdated`.
  const factory BridgeCommand.pinPlaceholder() = BridgeCommand_PinPlaceholder;

  /// History retrieval re-running a past utterance (see `RectifyText`).
  /// `style` pins the session's one-time style pick (ticket 23's named
  /// scenarios, ticket 28's 默认); `Live` runs under the live selection.
  /// `source_session_id` names the history row being re-run (another
  /// pass-through: the store records it as the new session's 来源会话).
  const factory BridgeCommand.rectifyText({
    required String rawTranscript,
    required BridgeSessionStyle style,
    PlatformInt64? sourceSessionId,
  }) = BridgeCommand_RectifyText;
}

@freezed
sealed class BridgeEvent with _$BridgeEvent {
  const BridgeEvent._();

  const factory BridgeEvent.sessionStateChanged({
    required BridgeSessionState from,
    required BridgeSessionState to,
  }) = BridgeEvent_SessionStateChanged;
  const factory BridgeEvent.liveTranscriptUpdated({required String text}) =
      BridgeEvent_LiveTranscriptUpdated;
  const factory BridgeEvent.paragraphMarked() = BridgeEvent_ParagraphMarked;

  /// The recording session was upgraded to quick mode (ADR-0020): the
  /// held chord crossed the threshold with nothing pinned. The session
  /// window hangs the 聆听中 phase word and the pin-hotkey disarm off
  /// it.
  const factory BridgeEvent.quickMarked() = BridgeEvent_QuickMarked;
  const factory BridgeEvent.speechActivityChanged({required bool speaking}) =
      BridgeEvent_SpeechActivityChanged;
  const factory BridgeEvent.rectifiedTextChunk({required String delta}) =
      BridgeEvent_RectifiedTextChunk;

  /// Thinking-channel text off the same rectify stream (14 号票,
  /// ADR-0019 item 6): the one-shot marquee's feed. Feedback material
  /// only — the shell keeps it out of the preview text and the
  /// insertion.
  const factory BridgeEvent.rectifyThinkingDelta({required String delta}) =
      BridgeEvent_RectifyThinkingDelta;

  /// The pin session's prefill table (ticket 18), arriving between
  /// the last chunk and the Preview state change.
  const factory BridgeEvent.previewPrefills({
    required List<BridgePrefillRow> prefills,
  }) = BridgeEvent_PreviewPrefills;
  const factory BridgeEvent.previewTextUpdated({required String text}) =
      BridgeEvent_PreviewTextUpdated;
  const factory BridgeEvent.textInserted({required String text}) =
      BridgeEvent_TextInserted;
  const factory BridgeEvent.error({required String message}) =
      BridgeEvent_Error;
}

/// Dart-side mirror of [`EventEnvelope`].
class BridgeEventEnvelope {
  final BigInt seq;
  final BigInt sessionId;
  final BigInt atMs;
  final BridgeEvent event;

  const BridgeEventEnvelope({
    required this.seq,
    required this.sessionId,
    required this.atMs,
    required this.event,
  });

  @override
  int get hashCode =>
      seq.hashCode ^ sessionId.hashCode ^ atMs.hashCode ^ event.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEventEnvelope &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          sessionId == other.sessionId &&
          atMs == other.atMs &&
          event == other.event;
}

/// Dart-side mirror of one confirm-time slot row: the slot's number
/// (its identity), the model's prefill for it ('' = none delivered),
/// and the value the confirm actually substituted (possibly ''). The
/// shell's slot document is the fact source and folds same-number
/// occurrences to one row; the engine ferries the table without
/// interpreting it.
class BridgePlaceholderFill {
  final int number;
  final String prefill;
  final String value;

  const BridgePlaceholderFill({
    required this.number,
    required this.prefill,
    required this.value,
  });

  @override
  int get hashCode => number.hashCode ^ prefill.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlaceholderFill &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          prefill == other.prefill &&
          value == other.value;
}

/// Dart-side mirror of one prefill-table row (【预填】 block row,
/// ticket 18): the slot's number and the model's initial value for it,
/// exactly as written — the shell's body-scan extraction decides which
/// identities exist and looks the rest up empty.
class BridgePrefillRow {
  final int number;
  final String value;

  const BridgePrefillRow({required this.number, required this.value});

  @override
  int get hashCode => number.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePrefillRow &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          value == other.value;
}

/// Dart-side mirror of [`SessionState`].
enum BridgeSessionState {
  idle,
  recording,
  rectifying,
  preview,
  inserted,
  cancelled,
}

@freezed
sealed class BridgeSessionStyle with _$BridgeSessionStyle {
  const BridgeSessionStyle._();

  const factory BridgeSessionStyle.live() = BridgeSessionStyle_Live;

  /// `scenario` is the pick's name (a pass-through; `None` for a
  /// directive pinned without a library entry).
  const factory BridgeSessionStyle.directive({
    required String text,
    String? scenario,
  }) = BridgeSessionStyle_Directive;
  const factory BridgeSessionStyle.defaultRegister() =
      BridgeSessionStyle_DefaultRegister;
}
