// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'history.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `history_config_err`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// The most recent stored sessions, newest first — the history panel's
/// content, read through the sessions⋈scenarios view with the scenario
/// scope the settings pane's chip row selects (the quick panel's slice
/// always asks for [`BridgeHistoryFilter::All`]). Empty in the
/// keep-nothing mode (and on the fake engine's ephemeral store).
Future<List<BridgeHistoryEntry>> historyList({
  required BridgeHistoryFilter filter,
}) => RustLib.instance.api.crateApiHistoryHistoryList(filter: filter);

/// Remove every stored session — the tray's one-click clear (the
/// placeholders go with them, by CASCADE). A no-op in the keep-nothing
/// mode.
Future<void> historyClear() =>
    RustLib.instance.api.crateApiHistoryHistoryClear();

/// The effective `[history]` settings from the layer files — the
/// settings window's history pane initial paint.
Future<BridgeHistoryConfig> historyConfig() =>
    RustLib.instance.api.crateApiHistoryHistoryConfig();

/// Write new `[history]` settings and apply them to the live store at
/// once (the settings window's 保留期 / 不留存 controls): the file edit
/// is section-preserving in the layer that owns the effective values,
/// and the store adopts the new config immediately — a tightened
/// retention sweeps at once, keep-nothing clears the sessions rows (the
/// database itself stays, as the scenarios' and terms' home), and
/// turning it back on resumes recording. Returns the re-read effective
/// config.
Future<BridgeHistoryConfig> setHistoryConfig({
  required bool enabled,
  required BigInt retentionDays,
}) => RustLib.instance.api.crateApiHistorySetHistoryConfig(
  enabled: enabled,
  retentionDays: retentionDays,
);

/// Dart-side mirror of the `[history]` settings (保留期 / 不留存).
class BridgeHistoryConfig {
  final bool enabled;
  final BigInt retentionDays;

  const BridgeHistoryConfig({
    required this.enabled,
    required this.retentionDays,
  });

  @override
  int get hashCode => enabled.hashCode ^ retentionDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          retentionDays == other.retentionDays;
}

/// Dart-side mirror of the history store's row: one stored session.
/// `scenario_id` is the row's scenario (`None` = 未选场景, the default
/// register).
class BridgeHistoryEntry {
  final PlatformInt64 id;

  /// Unix-epoch milliseconds, for the panel's timestamps.
  final BigInt createdAtMs;
  final String rawTranscript;
  final String rectifiedText;
  final PlatformInt64? scenarioId;

  const BridgeHistoryEntry({
    required this.id,
    required this.createdAtMs,
    required this.rawTranscript,
    required this.rectifiedText,
    this.scenarioId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAtMs.hashCode ^
      rawTranscript.hashCode ^
      rectifiedText.hashCode ^
      scenarioId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAtMs == other.createdAtMs &&
          rawTranscript == other.rawTranscript &&
          rectifiedText == other.rectifiedText &&
          scenarioId == other.scenarioId;
}

@freezed
sealed class BridgeHistoryFilter with _$BridgeHistoryFilter {
  const BridgeHistoryFilter._();

  const factory BridgeHistoryFilter.all() = BridgeHistoryFilter_All;
  const factory BridgeHistoryFilter.defaultRegister() =
      BridgeHistoryFilter_DefaultRegister;
  const factory BridgeHistoryFilter.scenario(PlatformInt64 field0) =
      BridgeHistoryFilter_Scenario;
}
