// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`

/// The hotword dictionary as it stands now, in stored order — the quick
/// panel's term chips. Store-level, engine-independent (the engine
/// re-reads the table when the next session opens, which is what makes a
/// quick-added term live for that session).
Future<List<String>> termsList() =>
    RustLib.instance.api.crateApiLibraryTermsList();

/// Quick-add one term to the dictionary (idempotent; blank rejected;
/// appended at the end of the order).
Future<void> appendTerm({required String term}) =>
    RustLib.instance.api.crateApiLibraryAppendTerm(term: term);

/// Remove a term from the dictionary (a no-op when absent; the positions
/// close the gap inside the same transaction).
Future<void> removeTerm({required String term}) =>
    RustLib.instance.api.crateApiLibraryRemoveTerm(term: term);

/// The scenario library (场景库): user-named style directives from the
/// store, in editor order. The shell paints its pickers from the list
/// and resolves the selected entry's directive text itself (selection
/// lives app-side, never persisted; ADR-0004).
Future<List<BridgeScenario>> scenarios() =>
    RustLib.instance.api.crateApiLibraryScenarios();

/// Save the whole scenario library — the settings editor's model,
/// wholesale — into the store: one transaction that updates identified
/// rows in place (a rename keeps its identity and its history
/// references), inserts the new ones, deletes the rest. Store-level and
/// engine-independent like [`scenarios`]: the pickers re-read the
/// library after a save; the selected scenario's directive rides the
/// next `SetStyleDirective` as usual. Only ever runs on a user action
/// (the editor's add/edit/delete), never on load.
Future<void> saveScenarios({required List<BridgeScenario> scenarios}) =>
    RustLib.instance.api.crateApiLibrarySaveScenarios(scenarios: scenarios);

/// The global directive (全局指令, ticket 22): the single `directive` key
/// from the app-owned `spokenrectifier-global.toml` — a companion file of
/// the scenario library's, so a library rewrite cannot lose it. A
/// missing, corrupt, or blank file reads as `None` (unset); this never
/// errors and never writes. The shell pushes the text at the engine via
/// `SetGlobalDirective` and repaints its preview from this same read.
Future<String?> globalDirective() =>
    RustLib.instance.api.crateApiLibraryGlobalDirective();

/// Save the global directive into the file the loader resolves (created
/// in the app's settings home when none exists yet). `None` and blank
/// text both write the canonical unset form — clearing the field and
/// saving is the off switch. File-level and engine-independent like
/// [`global_directive`]: the main window re-reads the file and pushes the
/// fresh text at the engine (`SetGlobalDirective`) on the
/// global-changed event. Only ever runs on a user action.
Future<void> saveGlobalDirective({String? directive}) => RustLib.instance.api
    .crateApiLibrarySaveGlobalDirective(directive: directive);

/// Rename a term in the dictionary, in place (the settings editor's 改;
/// the quick panel's quick-add and quick-remove stay the same calls).
/// Renaming onto a held spelling is refused.
Future<void> updateTerm({required String old, required String new_}) =>
    RustLib.instance.api.crateApiLibraryUpdateTerm(old: old, new_: new_);

/// Dart-side mirror of one scenario (场景): a user-named style directive
/// from the scenario library. `id` carries the table row's identity —
/// `None` only on an entry the editor has not saved yet — so a rename
/// keeps it and the history rows referencing the scenario with it.
class BridgeScenario {
  final PlatformInt64? id;
  final String name;
  final String directive;

  const BridgeScenario({this.id, required this.name, required this.directive});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ directive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeScenario &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          directive == other.directive;
}
