// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_policy`, `rectify_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// The effective `[rectify]` behavior from the layer files — the
/// rectify pane's initial paint, legacy `[llm]` keys already folded in
/// through the grandfather (ADR-0015). File-level and
/// engine-independent: the client adopts the keys at its (re)build, and
/// the window's save re-adopts at once via [`apply_connection_configs`].
Future<BridgeRectifyBehavior> rectifyBehavior() =>
    RustLib.instance.api.crateApiRectifyRectifyBehavior();

/// Write the rectify editor's whole model back into the layer files (see
/// `save_rectify_behavior`: the owning layers, the per-layer legacy-key
/// translation on the first save, the extra directive's blank-removal)
/// and return the re-read view — the files' truth, not the ask. No
/// combination validation rides this path: a thinking-off × prefill-on
/// tier saves fine, the pane's live warning is presentation only
/// (`.scratch/settings-window/issues/08`, ruling 4). The window calls
/// [`apply_connection_configs`] right after — the next attempt runs the
/// new behavior.
Future<BridgeRectifyBehavior> setRectifyBehavior({
  required BridgeRectifyBehavior edit,
}) => RustLib.instance.api.crateApiRectifySetRectifyBehavior(edit: edit);

/// The `[rectify]` behavior as the settings pane paints and saves it:
/// both tiers' thinking policy and prefill, the light-touch master
/// switch, threshold, and extra directive (ADR-0015/0016), plus the
/// quick-mode sub-section (ADR-0020). One struct both ways — the read
/// paints the initial form, the save writes exactly the model it
/// receives. The thinking policy rides the wire as its lowercase string;
/// `light_touch_extra_directive` and `quick_extra_directive` are `None`
/// when unset (empty saves remove the key).
class BridgeRectifyBehavior {
  /// `always` | `placeholders` | `off` (ADR-0015).
  final String fullThinkingPolicy;
  final bool fullPrefill;
  final bool lightTouchEnabled;
  final BigInt lightTouchMaxChars;
  final String lightTouchThinkingPolicy;
  final bool lightTouchPrefill;
  final String? lightTouchExtraDirective;

  /// `[rectify.quick]` (ADR-0020): holding the main hotkey past the
  /// threshold upgrades the session, which then skips preview and
  /// pastes on its own. `quick_enabled` is the master switch (off by
  /// default: no hold upgrades anything), `quick_rectify` whether the
  /// session still rectifies (off = paste the raw transcript),
  /// `quick_extra_directive` the quick-mode-only directive (`None` =
  /// unset; an empty save removes the key).
  final bool quickEnabled;
  final bool quickRectify;
  final String? quickExtraDirective;

  /// The CONNECTION domain's thinking reading (`on` / `off` /
  /// `unconfigured` / `broken`): the two cards' thinking-policy chips
  /// are disabled and the combination warning silenced while the
  /// connection's fields are inert (ADR-0019 item 3; design-spec
  /// §4.4's 修正 section). Carried on this read because the cards
  /// paint from it and nothing else — one round trip, and a chip
  /// click's re-read keeps the disable state fresh.
  final String connectionThinking;

  const BridgeRectifyBehavior({
    required this.fullThinkingPolicy,
    required this.fullPrefill,
    required this.lightTouchEnabled,
    required this.lightTouchMaxChars,
    required this.lightTouchThinkingPolicy,
    required this.lightTouchPrefill,
    this.lightTouchExtraDirective,
    required this.quickEnabled,
    required this.quickRectify,
    this.quickExtraDirective,
    required this.connectionThinking,
  });

  @override
  int get hashCode =>
      fullThinkingPolicy.hashCode ^
      fullPrefill.hashCode ^
      lightTouchEnabled.hashCode ^
      lightTouchMaxChars.hashCode ^
      lightTouchThinkingPolicy.hashCode ^
      lightTouchPrefill.hashCode ^
      lightTouchExtraDirective.hashCode ^
      quickEnabled.hashCode ^
      quickRectify.hashCode ^
      quickExtraDirective.hashCode ^
      connectionThinking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRectifyBehavior &&
          runtimeType == other.runtimeType &&
          fullThinkingPolicy == other.fullThinkingPolicy &&
          fullPrefill == other.fullPrefill &&
          lightTouchEnabled == other.lightTouchEnabled &&
          lightTouchMaxChars == other.lightTouchMaxChars &&
          lightTouchThinkingPolicy == other.lightTouchThinkingPolicy &&
          lightTouchPrefill == other.lightTouchPrefill &&
          lightTouchExtraDirective == other.lightTouchExtraDirective &&
          quickEnabled == other.quickEnabled &&
          quickRectify == other.quickRectify &&
          quickExtraDirective == other.quickExtraDirective &&
          connectionThinking == other.connectionThinking;
}
